syntax = "proto3";
// Recovered from Cortex Control.app  (file: ProductionAutomation.proto)
package cortex_protobuf_v2;
import "Preset.proto";
message CortexMessageType {
  enum Enum {
    Undefined = 0;
    Grid = 1;
    SetlistPosition = 2;
    IOSettings = 3;
    File = 4;
    IOMeter = 5;
    Tuner = 6;
    Diagnostics = 7;
    MIDISettings = 8;
    GeneralSettings = 9;
    Version = 10;
    ProductionAutomationMode = 11;
    GridMove = 12;
    Scene = 13;
    Mode = 14;
    RecallPreset = 15;
    EnableCaptureOut = 16;
    MasterVolume = 17;
    CloudLogin = 18;
    DefaultParameters = 19;
    RecentsFavorites = 20;
    UndoRedo = 21;
    SceneCopy = 22;
    SceneLabel = 23;
    ShowGigView = 24;
    Screenshot = 25;
    CPULoad = 26;
    ShowTuner = 27;
    Looper = 28;
    ProductForward = 29;
    BackupsForward = 30;
    LogsForward = 31;
    KeepAlive = 32;
    GlobalTempo = 33;
    PresetDirty = 34;
    ModuleStats = 35;
    NeuralCapture = 36;
    GridModelMeter = 37;
    GlobalEQ = 38;
    RecentSearches = 39;
    LocalBackup = 40;
    CloudBackup = 41;
    CompilerInhibitedModules = 42;
    SystemTimeSync = 43;
    Logs = 44;
    ProcessDownloadsQueue = 45;
    CloudProduct = 46;
    Confirmation = 47;
    SceneColor = 48;
    Connection = 49;
    NewModels = 50;
    ModelRepo = 51;
    ResetCommsBuffers = 52;
    SuspendConnection = 53;
    PinnedModels = 54;
    GigViewButton = 55;
    GenericError = 56;
    BulkOperation = 57;
    License = 58;
    PresetSpeedTest = 59;
    Updater = 60;
    UpdaterForward = 61;
    GainCalibration = 62;
    NeuralCapture2 = 63;
    Serialization = 64;
    TestFarm = 65;
    ProductionTest = 66;
    LoadAutomatedTestPreset = 67;
    SetTestPresetInputOutputPorts = 68;
    SetTestPresetSplitMixPoints = 69;
    GenerateTestPreset = 70;
    ModelPreset = 71;
    RemoteControl = 72;
    NumberOfMessageTypes = 73;
  }
}
message MessageAction {
  enum Enum {
    CREATE = 0;
    UPDATE = 1;
    DELETE = 2;
    READ = 3;
    MOVE = 4;
    COPY = 5;
    UPLOAD = 6;
    DOWNLOAD = 7;
    SWAP = 8;
  }
}
message HTTPOperation {
  enum Enum {
    GET = 0;
    PUT = 1;
    POST = 2;
    DELETE = 3;
  }
}
message LooperUpdateType {
  enum Enum {
    METER = 0;
    BUTTONS = 1;
  }
}
message RecallPresetReason {
  enum Enum {
    OTHER = 0;
    UNDO = 1;
    SAVE = 2;
  }
}
message VersionMessage {
  enum DeviceType {
    QC = 0;
    ATMA = 1;
  }
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _linux_kernel_version {
    string linux_kernel_version = 3;
  }
  oneof _zenos_git_hash {
    string zenos_git_hash = 4;
  }
  oneof _zenwireless_fw_version {
    string zenwireless_fw_version = 5;
  }
  oneof _uboot_version {
    string uboot_version = 6;
  }
  oneof _app_fw_version {
    string app_fw_version = 7;
  }
  oneof _bootloader_fw_version {
    string bootloader_fw_version = 8;
  }
  oneof _device_serial_number {
    string device_serial_number = 9;
  }
  oneof _comms_version {
    bytes comms_version = 10;
  }
  oneof _device_type {
    cortex_protobuf_v2.VersionMessage.DeviceType device_type = 12;
  }
  oneof _is_ess {
    bool is_ess = 13;
  }
  oneof _custom_name {
    string custom_name = 15;
  }
  oneof _mac_address {
    string mac_address = 16;
  }
  oneof _zencoder_fw_app {
    string zencoder_fw_app = 17;
  }
  oneof _zencoder_fw_bootloader {
    string zencoder_fw_bootloader = 18;
  }
  oneof _cortex_control_version {
    string cortex_control_version = 11;
  }
  oneof _cortex_control_version_valid {
    bool cortex_control_version_valid = 14;
  }
}
message HeadphonesFeedLevel {
  float level = 1;
  uint32 output_port_id = 2;
}
message InputPortSettings {
  uint32 input_port_id = 1;
  oneof _level {
    float level = 2;
  }
  oneof _input_zmode {
    float input_zmode = 3;
  }
  oneof _input_type {
    float input_type = 4;
  }
  oneof _ground_lift {
    float ground_lift = 5;
  }
  oneof _plugged {
    bool plugged = 6;
  }
}
message OutputPortSettings {
  uint32 output_port_id = 1;
  oneof _level {
    float level = 2;
  }
  oneof _ground_lift {
    float ground_lift = 3;
  }
  oneof _mute {
    bool mute = 4;
  }
  oneof _plugged {
    bool plugged = 5;
  }
}
message HeadphonesSettings {
  repeated cortex_protobuf_v2.HeadphonesFeedLevel hp_feed = 2;
  oneof _level {
    float level = 1;
  }
  oneof _plugged {
    bool plugged = 3;
  }
}
message USBPortSettings {
  oneof _level {
    float level = 1;
  }
  oneof _hp_select {
    float hp_select = 2;
  }
  oneof _plugged {
    bool plugged = 3;
  }
  oneof _dry_wet {
    float dry_wet = 4;
  }
}
message ExpPortSettings {
  int32 exp_port_id = 1;
  oneof _plugged {
    bool plugged = 2;
  }
  oneof _level {
    float level = 3;
  }
  oneof _calibrating {
    bool calibrating = 4;
  }
}
message MIDIPortSettings {
  oneof _midi_thru {
    float midi_thru = 1;
  }
}
message PortSettings {
  repeated cortex_protobuf_v2.InputPortSettings in_port = 1;
  repeated cortex_protobuf_v2.OutputPortSettings out_port = 2;
  repeated cortex_protobuf_v2.ExpPortSettings exp_port = 6;
  oneof _hp_port {
    cortex_protobuf_v2.HeadphonesSettings hp_port = 3;
  }
  oneof _usb_port {
    cortex_protobuf_v2.USBPortSettings usb_port = 4;
  }
  oneof _midi_port {
    cortex_protobuf_v2.MIDIPortSettings midi_port = 5;
  }
}
message IOSettingsMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _settings {
    cortex_protobuf_v2.PortSettings settings = 3;
  }
  oneof _xlr1_2_linked {
    bool xlr1_2_linked = 4;
  }
  oneof _out3_4_linked {
    bool out3_4_linked = 5;
  }
}
message GridMessage {
  enum UpdateType {
    METER_UPDATE = 0;
  }
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _preset {
    BinaryPreset preset = 3;
  }
  oneof _update_type {
    cortex_protobuf_v2.GridMessage.UpdateType update_type = 4;
  }
}
message RecallPresetMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _preset {
    BinaryPreset preset = 3;
  }
  oneof _reason {
    cortex_protobuf_v2.RecallPresetReason.Enum reason = 4;
  }
}
message SceneMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _selected_scene {
    uint32 selected_scene = 3;
  }
}
message GridMoveElement {
  uint32 from_row = 1;
  uint32 from_col = 2;
  uint32 to_row = 3;
  uint32 to_col = 4;
  bool is_drop = 5;
}
message GridMoveRow {
  repeated uint32 modelIds = 1;
}
message GridMoveGrid {
  repeated cortex_protobuf_v2.GridMoveRow rows = 1;
}
message GridMoveMessage {
  repeated cortex_protobuf_v2.GridMoveElement move = 2;
  oneof _request_id {
    uint64 request_id = 1;
  }
  oneof _grid {
    cortex_protobuf_v2.GridMoveGrid grid = 3;
  }
}
message SetlistPositionMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _folder_key {
    string folder_key = 3;
  }
  oneof _position {
    uint32 position = 4;
  }
  oneof _is_factory {
    bool is_factory = 5;
  }
  oneof _is_downloads {
    bool is_downloads = 6;
  }
  oneof _key_in_downloads {
    string key_in_downloads = 7;
  }
  oneof _is_plugin {
    bool is_plugin = 8;
  }
  oneof _key_in_plugin_folder {
    string key_in_plugin_folder = 9;
  }
}
message DSPCommsDiagnosticsMessage {
  uint32 status1 = 1;
  uint32 status2 = 2;
  uint32 status3 = 3;
  uint32 status4 = 4;
  float process_cpu = 5;
  float internal_heap_usage = 6;
  float external_heap_usage = 7;
  float internal_pm_heap_usage = 8;
  float process_cpu_max = 9;
  float ext_dma_usage = 10;
  uint32 error_flags = 11;
}
message SOC2ARMCommsDiagnosticsMessage {
  uint32 USBConnected = 1;
  uint32 inReadIdx = 2;
  uint32 inWriteIdx = 3;
  uint32 outReadIdx = 4;
  uint32 outWriteIdx = 5;
  uint64 USBAudioRxFrame = 6;
  uint64 USBAudioTxFrame = 7;
  uint32 USBAudioTxFrameSkipped = 8;
  uint32 USBAudioTxFrameAborted = 9;
  uint32 USBAudioOutRdWrDistanceAverage = 10;
  uint32 USBAudioRdWrMinNumSamples = 11;
  uint32 USBAudioRdWrMaxNumSamples = 12;
  uint32 USBAudioPlusOneSampleCount = 13;
  uint32 USBAudioMinusOneSampleCount = 14;
  uint32 USBAudioFeedbackState = 15;
  uint32 USBAudioStreamingEPEnabled = 16;
  uint32 USBAudioStreamingEPDisabled = 17;
  uint64 USBMidiOutCount = 18;
  uint64 USBMidiInCount = 19;
  uint64 USBHIDInCount = 20;
  uint64 USBHIDOutCount = 21;
  uint32 USBHIDInDroppedCount = 22;
  uint32 USBHIDOutDroppedCount = 23;
}
message DiagnosticsMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _SOC1Core1Diagnostics {
    cortex_protobuf_v2.DSPCommsDiagnosticsMessage SOC1Core1Diagnostics = 3;
  }
  oneof _SOC1Core2Diagnostics {
    cortex_protobuf_v2.DSPCommsDiagnosticsMessage SOC1Core2Diagnostics = 4;
  }
  oneof _SOC2Core1Diagnostics {
    cortex_protobuf_v2.DSPCommsDiagnosticsMessage SOC2Core1Diagnostics = 5;
  }
  oneof _SOC2Core2Diagnostics {
    cortex_protobuf_v2.DSPCommsDiagnosticsMessage SOC2Core2Diagnostics = 6;
  }
  oneof _SOC2ARMCoreDiagnostics {
    cortex_protobuf_v2.SOC2ARMCommsDiagnosticsMessage SOC2ARMCoreDiagnostics = 7;
  }
  oneof _soc1_to_soc2_dropped_count {
    uint64 soc1_to_soc2_dropped_count = 8;
  }
}
message ProductionAutomationModeMessage {
  bool enable = 2;
  oneof _request_id {
    uint64 request_id = 1;
  }
}
message ProductDependency {
  string hash = 1;
  oneof _missing {
    int32 missing = 2;
  }
  oneof _visible {
    int32 visible = 3;
  }
  oneof _published {
    int32 published = 4;
  }
  oneof _cloud_id {
    string cloud_id = 5;
  }
  oneof _name {
    string name = 6;
  }
  oneof _product_type {
    string product_type = 7;
  }
}
message ProductData {
  repeated string tags = 7;
  repeated cortex_protobuf_v2.ProductDependency factory_dependencies = 13;
  repeated cortex_protobuf_v2.ProductDependency product_dependencies = 14;
  oneof _key {
    string key = 1;
  }
  oneof _index {
    int32 index = 2;
  }
  oneof _name {
    string name = 3;
  }
  oneof _author {
    string author = 4;
  }
  oneof _author_id {
    string author_id = 5;
  }
  oneof _coros_version {
    string coros_version = 6;
  }
  oneof _date {
    string date = 8;
  }
  oneof _gain {
    int32 gain = 9;
  }
  oneof _cloud_id {
    string cloud_id = 10;
  }
  oneof _description {
    string description = 11;
  }
  oneof _shared_by {
    string shared_by = 12;
  }
  oneof _instrument {
    int32 instrument = 15;
  }
  oneof _device {
    int32 device = 16;
  }
  oneof _extraMetadata {
    bytes extraMetadata = 17;
  }
  oneof _old_key {
    string old_key = 18;
  }
  oneof _is_readonly {
    bool is_readonly = 19;
  }
  oneof _version {
    string version = 20;
  }
  oneof _date_ms_since_epoch {
    int64 date_ms_since_epoch = 21;
  }
}
message FolderInfo {
  repeated cortex_protobuf_v2.ProductData files = 7;
  oneof _key {
    string key = 1;
  }
  oneof _parent_key {
    string parent_key = 2;
  }
  oneof _name {
    string name = 3;
  }
  oneof _is_factory {
    bool is_factory = 4;
  }
  oneof _is_downloads {
    bool is_downloads = 5;
  }
  oneof _is_user_default {
    bool is_user_default = 6;
  }
  oneof _is_cloud {
    bool is_cloud = 8;
  }
  oneof _is_favorites {
    bool is_favorites = 9;
  }
  oneof _is_plugin {
    bool is_plugin = 10;
  }
}
message FileMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _type {
    int32 type = 3;
  }
  oneof _folder {
    cortex_protobuf_v2.FolderInfo folder = 4;
  }
  oneof _to_folder {
    cortex_protobuf_v2.FolderInfo to_folder = 5;
  }
  oneof _short_listing {
    bool short_listing = 6;
  }
  oneof _ir_payload {
    bytes ir_payload = 7;
  }
  oneof _preset_payload {
    BinaryPreset preset_payload = 8;
  }
  oneof _total_bulk_create_count {
    int32 total_bulk_create_count = 9;
  }
  oneof _delete_from_library {
    bool delete_from_library = 10;
  }
}
message BulkOperationMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _progress_message {
    string progress_message = 3;
  }
  oneof _blocking {
    bool blocking = 4;
  }
  oneof _cancellable {
    bool cancellable = 5;
  }
  oneof _progress {
    float progress = 6;
  }
  oneof _finished {
    bool finished = 7;
  }
  oneof _is_multiselection_active {
    bool is_multiselection_active = 8;
  }
  oneof _type {
    int32 type = 9;
  }
  oneof _source_folder {
    cortex_protobuf_v2.FolderInfo source_folder = 10;
  }
  oneof _destination_folder {
    cortex_protobuf_v2.FolderInfo destination_folder = 11;
  }
}
message IOMeterMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _input_1 {
    float input_1 = 3;
  }
  oneof _input_2 {
    float input_2 = 4;
  }
  oneof _return_1 {
    float return_1 = 5;
  }
  oneof _return_2 {
    float return_2 = 6;
  }
  oneof _xlr_1 {
    float xlr_1 = 7;
  }
  oneof _xlr_1_limiter {
    float xlr_1_limiter = 8;
  }
  oneof _xlr_2 {
    float xlr_2 = 9;
  }
  oneof _xlr_2_limiter {
    float xlr_2_limiter = 10;
  }
  oneof _out_3 {
    float out_3 = 11;
  }
  oneof _out_3_limiter {
    float out_3_limiter = 12;
  }
  oneof _out_4 {
    float out_4 = 13;
  }
  oneof _out_4_limiter {
    float out_4_limiter = 14;
  }
  oneof _send_1 {
    float send_1 = 15;
  }
  oneof _send_2 {
    float send_2 = 16;
  }
  oneof _hp_l {
    float hp_l = 17;
  }
  oneof _hp_r {
    float hp_r = 18;
  }
  oneof _hp_limiter_active {
    bool hp_limiter_active = 19;
  }
  oneof _usb_output_1l {
    float usb_output_1l = 20;
  }
  oneof _usb_output_1r {
    float usb_output_1r = 21;
  }
  oneof _usb_output_2l {
    float usb_output_2l = 22;
  }
  oneof _usb_output_2r {
    float usb_output_2r = 23;
  }
  oneof _usb_output_3l {
    float usb_output_3l = 24;
  }
  oneof _usb_output_3r {
    float usb_output_3r = 25;
  }
  oneof _usb_output_4l {
    float usb_output_4l = 26;
  }
  oneof _usb_output_4r {
    float usb_output_4r = 27;
  }
  oneof _usb_input_1l {
    float usb_input_1l = 28;
  }
  oneof _usb_input_1r {
    float usb_input_1r = 29;
  }
  oneof _usb_input_2l {
    float usb_input_2l = 30;
  }
  oneof _usb_input_2r {
    float usb_input_2r = 31;
  }
  oneof _usb_input_3l {
    float usb_input_3l = 32;
  }
  oneof _usb_input_3r {
    float usb_input_3r = 33;
  }
  oneof _usb_input_4l {
    float usb_input_4l = 34;
  }
  oneof _usb_input_4r {
    float usb_input_4r = 35;
  }
  oneof _grid_xlr_1 {
    float grid_xlr_1 = 36;
  }
  oneof _grid_xlr_2 {
    float grid_xlr_2 = 37;
  }
  oneof _grid_out_3 {
    float grid_out_3 = 38;
  }
  oneof _grid_out_4 {
    float grid_out_4 = 39;
  }
  oneof _grid_send_1 {
    float grid_send_1 = 40;
  }
  oneof _grid_send_2 {
    float grid_send_2 = 41;
  }
}
message AvailableModes {
  repeated uint32 modes = 1;
}
message ModeMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _mode {
    uint32 mode = 3;
  }
  oneof _available_modes {
    cortex_protobuf_v2.AvailableModes available_modes = 4;
  }
  oneof _atma_page {
    uint32 atma_page = 5;
  }
}
message EnableCaptureOutMessage {
  bool enable = 2;
  oneof _request_id {
    uint64 request_id = 1;
  }
}
message MasterVolumeMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _volume {
    float volume = 3;
  }
  oneof _engaged {
    bool engaged = 4;
  }
  oneof _calibrate {
    bool calibrate = 5;
  }
}
message TunerMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _input_port_id {
    int32 input_port_id = 3;
  }
  oneof _frequency {
    float frequency = 4;
  }
  oneof _mute {
    bool mute = 5;
  }
  oneof _enable_meter {
    bool enable_meter = 6;
  }
  oneof _meter {
    float meter = 7;
  }
}
message AuthorizationToken {
  string access_token = 1;
  string refresh_token = 2;
  int32 expires_in = 3;
}
message CloudLoginMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _username {
    string username = 3;
  }
  oneof _token {
    cortex_protobuf_v2.AuthorizationToken token = 4;
  }
}
message DefaultParametersModel {
  string id = 1;
  Model model = 2;
}
message DefaultParametersMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  int32 row = 3;
  int32 column = 4;
  repeated cortex_protobuf_v2.DefaultParametersModel all_defaults = 5;
  oneof _request_id {
    uint64 request_id = 2;
  }
}
message RecentsFavoritesItem {
  string name = 1;
  string folder_key = 2;
  string folder_name = 3;
  bool is_factory = 4;
  bool is_plugin = 5;
}
message RecentsFavoritesMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  bool is_favorites = 3;
  repeated cortex_protobuf_v2.RecentsFavoritesItem items = 4;
  oneof _request_id {
    uint64 request_id = 2;
  }
}
message UndoRedoMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  repeated int32 undo_frames = 3;
  repeated int32 redo_frames = 4;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _undo {
    bool undo = 5;
  }
  oneof _redo {
    bool redo = 6;
  }
}
message SceneCopyMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  int32 from_index = 3;
  int32 to_index = 4;
  bool is_swap = 5;
  oneof _request_id {
    uint64 request_id = 2;
  }
}
message SceneLabelMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  int32 index = 3;
  string label = 4;
  oneof _request_id {
    uint64 request_id = 2;
  }
}
message ShowGigViewMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  bool show = 3;
  oneof _request_id {
    uint64 request_id = 2;
  }
}
message ScreenshotMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  string folder_name = 3;
  bool is_factory = 4;
  int32 index = 5;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _png {
    bytes png = 6;
  }
}
message CPUColumnLoad {
  float cpu_load = 1;
  bool is_on_core2 = 2;
}
message CPUChainLoad {
  repeated cortex_protobuf_v2.CPUColumnLoad columns = 1;
}
message CPULoadMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  repeated cortex_protobuf_v2.CPUChainLoad chains = 4;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _cpu_total_load {
    float cpu_total_load = 3;
  }
}
message ShowTunerMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  bool show = 3;
  oneof _request_id {
    uint64 request_id = 2;
  }
}
message LooperStatus {
  uint32 state = 1;
  float progress = 2;
  float undo_progress = 3;
  uint32 duplicate_cycle = 4;
  uint32 num_duplicate_cycles = 5;
  uint32 one_shot_stopped = 6;
  uint32 redo_available = 7;
  uint32 loop_length = 8;
  uint32 free_samples = 9;
  uint32 in_reverse = 10;
  uint32 one_shot = 11;
  uint32 half_speed = 12;
  uint32 fixed_duplicate_cycles = 13;
  uint32 armed = 14;
  uint32 waiting_for_cycle = 15;
  uint32 undo_count = 16;
  float max_write_displacement = 17;
  float min_write_displacement = 18;
  uint32 events_waiting_for_quantize = 19;
  uint32 current_clock = 20;
  uint32 transition = 21;
  uint32 action = 22;
}
message LooperMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _status {
    cortex_protobuf_v2.LooperStatus status = 3;
  }
  oneof _state {
    uint32 state = 4;
  }
  oneof _one_shot_play {
    bool one_shot_play = 5;
  }
  oneof _sync_start_waiting {
    bool sync_start_waiting = 6;
  }
  oneof _quantize_enabled {
    bool quantize_enabled = 7;
  }
  oneof _update_type {
    cortex_protobuf_v2.LooperUpdateType.Enum update_type = 8;
  }
}
message ProductForwardHeaderPair {
  string name = 1;
  string value = 2;
}
message ProductForwardRequest {
  cortex_protobuf_v2.HTTPOperation.Enum operation = 1;
  string url = 2;
  int32 timeout = 3;
  bool is_multipart = 4;
  repeated cortex_protobuf_v2.ProductForwardHeaderPair headers = 6;
  oneof _payload {
    bytes payload = 5;
  }
}
message ProductForwardResponse {
  bytes payload = 1;
  int32 error_code = 2;
}
message ProductForwardMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  uint64 cloud_request_id = 3;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _request {
    cortex_protobuf_v2.ProductForwardRequest request = 4;
  }
  oneof _response {
    cortex_protobuf_v2.ProductForwardResponse response = 5;
  }
}
message BackupsForwardRequestType {
  enum Enum {
    CREATE_OR_UPDATE = 0;
    DOWNLOAD = 1;
    RENAME = 2;
    DELETE = 3;
    LIST = 4;
    FETCH_URL = 5;
    UPLOAD_STATUS = 6;
  }
}
message BackupsForwardRequest {
  cortex_protobuf_v2.BackupsForwardRequestType.Enum type = 1;
  bytes payload = 3;
  repeated cortex_protobuf_v2.ProductForwardHeaderPair headers = 6;
  oneof _url {
    string url = 2;
  }
  oneof _is_last_chunk {
    bool is_last_chunk = 4;
  }
  oneof _timeout {
    int32 timeout = 5;
  }
}
message BackupsForwardResponse {
  bytes payload = 1;
  oneof _is_last_chunk {
    bool is_last_chunk = 2;
  }
  oneof _error_code {
    int32 error_code = 3;
  }
}
message BackupsForwardMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  uint64 backups_request_id = 3;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _request {
    cortex_protobuf_v2.BackupsForwardRequest request = 4;
  }
  oneof _response {
    cortex_protobuf_v2.BackupsForwardResponse response = 5;
  }
}
message LogsForwardRequestType {
  enum Enum {
    FETCH_URLS = 0;
    UPLOAD_LOGS = 1;
    UPLOAD_COREDUMP = 2;
  }
}
message LogsForwardRequest {
  cortex_protobuf_v2.LogsForwardRequestType.Enum type = 1;
  bytes payload = 3;
  repeated cortex_protobuf_v2.ProductForwardHeaderPair headers = 6;
  oneof _url {
    string url = 2;
  }
  oneof _is_last_chunk {
    bool is_last_chunk = 4;
  }
  oneof _timeout {
    int32 timeout = 5;
  }
}
message LogsForwardResponse {
  bytes payload = 1;
  int32 error_code = 2;
}
message LogsForwardMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  uint64 logs_request_id = 3;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _request {
    cortex_protobuf_v2.LogsForwardRequest request = 4;
  }
  oneof _response {
    cortex_protobuf_v2.LogsForwardResponse response = 5;
  }
}
message KeepAliveMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  bool is_online = 3;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _timeout {
    float timeout = 4;
  }
}
message GeneralMIDIMessage {
  repeated MidiMessageInfo msg = 2;
  oneof _source {
    uint32 source = 1;
  }
}
message GeneralMIDIMessages {
  repeated cortex_protobuf_v2.GeneralMIDIMessage messages = 1;
}
message MIDISettingsMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _preset_load_messages {
    cortex_protobuf_v2.GeneralMIDIMessages preset_load_messages = 3;
  }
  oneof _general_midi_messages {
    cortex_protobuf_v2.GeneralMIDIMessages general_midi_messages = 4;
  }
}
message MetronomeStatusUpdate {
  uint32 is_enabled = 1;
  uint32 preroll_enabled = 2;
  uint32 current_beat = 3;
  uint32 current_bar = 4;
  uint32 current_tick = 5;
  int32 count_in_beats_remaining = 6;
  int32 count_in_bars_remaining = 7;
}
message GlobalTempoMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  repeated Param params = 3;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _metronome_status {
    cortex_protobuf_v2.MetronomeStatusUpdate metronome_status = 4;
  }
}
message PresetDirtyMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  bool is_dirty = 3;
  oneof _request_id {
    uint64 request_id = 2;
  }
}
message GlobalBypassRows {
  bool row1 = 1;
  bool row2 = 2;
  bool row3 = 3;
  bool row4 = 4;
}
message SceneBlockBypass {
  enum Enum {
    ALWAYS_OVERWRITE = 0;
    NONSTOMP_OVERWRITE = 1;
    NEVER_OVERWRITE = 2;
  }
}
message CloudDomain {
  enum Enum {
    DEFAULT_DOMAIN = 0;
    ALTERNATIVE_DOMAIN = 1;
  }
}
message PowerOptions {
  enum Enum {
    SHUTDOWN = 0;
    REBOOT = 1;
    STANDBY = 2;
    WAKE_UP = 3;
  }
}
message AtmaPowerOnMode {
  enum Enum {
    POWER_BUTTON = 0;
    POWER_ON_WHEN_PLUGGED_IN = 1;
  }
}
message MasterVolumeAssignmentOptions {
  bool out12 = 1;
  bool out34 = 2;
  bool send12 = 3;
  bool headphones = 4;
}
message MidiClockOut {
  enum Enum {
    OFF = 0;
    MIDI_DIN_ONLY = 1;
    USB_MIDI_ONLY = 2;
    BOTH_USB_AND_DIN_MIDI = 3;
  }
}
message DownloadDestinationFolder {
  string key = 1;
  int32 type = 2;
}
message StorageInfoType {
  enum Enum {
    PRESETS = 0;
    NEURAL_CAPTURES = 1;
    IMPULSE_RESPONSES = 2;
  }
}
message StorageInfoEntity {
  cortex_protobuf_v2.StorageInfoType.Enum entity_type = 1;
  int32 size_maximum = 2;
  int32 size_current = 3;
}
message StorageInfo {
  int64 total_storage_size_kb = 1;
  int64 free_storage_size_kb = 2;
  repeated cortex_protobuf_v2.StorageInfoEntity storage_entities = 3;
}
message GeneralSettingsMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  repeated cortex_protobuf_v2.DownloadDestinationFolder download_destination_folders = 25;
  repeated int32 looper_stomp_assignments = 33;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _reset_wifi_networks {
    bool reset_wifi_networks = 3;
  }
  oneof _screen_brightness {
    int32 screen_brightness = 4;
  }
  oneof _led_brightness {
    int32 led_brightness = 5;
  }
  oneof _lock_screen_and_volume_knob {
    bool lock_screen_and_volume_knob = 6;
  }
  oneof _global_bypass_cab {
    cortex_protobuf_v2.GlobalBypassRows global_bypass_cab = 7;
  }
  oneof _global_bypass_ir {
    cortex_protobuf_v2.GlobalBypassRows global_bypass_ir = 8;
  }
  oneof _scene_block_bypass {
    cortex_protobuf_v2.SceneBlockBypass.Enum scene_block_bypass = 9;
  }
  oneof _midi_over_usb {
    bool midi_over_usb = 10;
  }
  oneof _midi_channel {
    int32 midi_channel = 11;
  }
  oneof _ignore_duplicate_pc {
    bool ignore_duplicate_pc = 12;
  }
  oneof _power_option {
    cortex_protobuf_v2.PowerOptions.Enum power_option = 13;
  }
  oneof _power_button_sensitivity {
    int32 power_button_sensitivity = 14;
  }
  oneof _reset_settings {
    bool reset_settings = 15;
  }
  oneof _factory_reset {
    bool factory_reset = 16;
  }
  oneof _available_disk_space {
    float available_disk_space = 17;
  }
  oneof _total_disk_space {
    float total_disk_space = 18;
  }
  oneof _internal_midi_clock_enabled {
    bool internal_midi_clock_enabled = 19;
  }
  oneof _cloud_endpoint {
    string cloud_endpoint = 20;
  }
  oneof _master_volume_assignment {
    cortex_protobuf_v2.MasterVolumeAssignmentOptions master_volume_assignment = 21;
  }
  oneof _stomp_mode_auto_assign {
    bool stomp_mode_auto_assign = 22;
  }
  oneof _swap_tempo_tuner_access {
    bool swap_tempo_tuner_access = 23;
  }
  oneof _midi_clock_out {
    cortex_protobuf_v2.MidiClockOut.Enum midi_clock_out = 24;
  }
  oneof _disable_internet_connection_check {
    bool disable_internet_connection_check = 26;
  }
  oneof _enable_dynamic_delay_compensation {
    bool enable_dynamic_delay_compensation = 27;
  }
  oneof _dimmed_led_brightness {
    int32 dimmed_led_brightness = 28;
  }
  oneof _enable_preset_dimmed {
    bool enable_preset_dimmed = 29;
  }
  oneof _enable_scene_dimmed {
    bool enable_scene_dimmed = 30;
  }
  oneof _enable_stomp_dimmed {
    bool enable_stomp_dimmed = 31;
  }
  oneof _atma_power_mode {
    cortex_protobuf_v2.AtmaPowerOnMode.Enum atma_power_mode = 32;
  }
  oneof _midi_clock_in_enabled {
    bool midi_clock_in_enabled = 34;
  }
  oneof _atma_looper_lock_mode {
    bool atma_looper_lock_mode = 35;
  }
  oneof _storage_info {
    cortex_protobuf_v2.StorageInfo storage_info = 36;
  }
  oneof _cloud_domain {
    cortex_protobuf_v2.CloudDomain.Enum cloud_domain = 37;
  }
  oneof _gig_view_stomp_access_enabled {
    bool gig_view_stomp_access_enabled = 38;
  }
  oneof _hold_timing {
    int32 hold_timing = 39;
  }
}
message ModuleStatsItem {
  uint32 id = 1;
  float cpu_percent = 2;
  uint32 dm_heap_bytes = 3;
  uint32 pm_heap_bytes = 4;
  uint32 sd_heap_bytes = 5;
  uint32 dmda_bytes = 6;
  uint32 pmda_bytes = 7;
  uint32 pmco_bytes = 8;
  float edma_percent = 9;
  int32 singletons = 10;
  int32 latency = 11;
  bool reuse_pmco = 12;
  bool has_sidechain = 13;
}
message ModuleStatsSizeRelationPair {
  repeated uint32 smaller_models = 1;
  repeated uint32 larger_models = 2;
}
message ModuleStatsSizeRelation {
  uint32 id = 1;
  cortex_protobuf_v2.ModuleStatsSizeRelationPair relations = 2;
}
message ModuleStatsValidModelId {
  uint32 id = 1;
  bool valid = 2;
}
message ModuleStatsMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  repeated cortex_protobuf_v2.ModuleStatsItem stats = 3;
  repeated cortex_protobuf_v2.ModuleStatsSizeRelation size_relations = 4;
  repeated cortex_protobuf_v2.ModuleStatsValidModelId valid_id = 5;
  repeated cortex_protobuf_v2.ModuleStatsItem core_stats = 6;
  oneof _request_id {
    uint64 request_id = 2;
  }
}
message NeuralCaptureParameter {
  int32 index = 1;
  float value = 2;
}
message NeuralCaptureSaveInfo {
  string name = 1;
  int32 device = 2;
  int32 instrument = 3;
}
message NeuralCaptureMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  repeated cortex_protobuf_v2.NeuralCaptureParameter parameters = 7;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _try_to_show_dialog {
    bool try_to_show_dialog = 3;
  }
  oneof _show_dialog_fail_reason {
    string show_dialog_fail_reason = 4;
  }
  oneof _show_dialog {
    bool show_dialog = 5;
  }
  oneof _state {
    int32 state = 6;
  }
  oneof _progress {
    int32 progress = 8;
  }
  oneof _toggle_ab_model {
    bool toggle_ab_model = 9;
  }
  oneof _save_info {
    cortex_protobuf_v2.NeuralCaptureSaveInfo save_info = 10;
  }
  oneof _error_id {
    int32 error_id = 11;
  }
  oneof _model_ab_bypass {
    bool model_ab_bypass = 12;
  }
  oneof _model_ab {
    Model model_ab = 13;
  }
}
message GridModelMeterMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _row {
    int32 row = 3;
  }
  oneof _column {
    int32 column = 4;
  }
}
message GlobalEQParameter {
  int32 parameter_index = 1;
  float value = 2;
}
message GlobalEQMessage {
  enum DefaultParameterAction {
    RESET_TO_FACTORY = 0;
    RESET_TO_USER = 1;
    SET = 2;
  }
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  repeated cortex_protobuf_v2.GlobalEQParameter parameters = 3;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _bypassed {
    bool bypassed = 4;
  }
  oneof _has_user_defaults {
    bool has_user_defaults = 5;
  }
  oneof _default_parameter_action {
    cortex_protobuf_v2.GlobalEQMessage.DefaultParameterAction default_parameter_action = 6;
  }
}
message RecentSearchesMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  repeated string searches = 3;
  oneof _request_id {
    uint64 request_id = 2;
  }
}
message LocalBackupMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _backup_json {
    string backup_json = 3;
  }
  oneof _can_apply_backup {
    bool can_apply_backup = 4;
  }
  oneof _applied_backup {
    bool applied_backup = 5;
  }
  oneof _is_last_chunk {
    bool is_last_chunk = 6;
  }
}
message CloudBackupItem {
  oneof _user_id {
    string user_id = 1;
  }
  oneof _client_type {
    string client_type = 2;
  }
  oneof _client_version {
    string client_version = 3;
  }
  oneof _name {
    string name = 4;
  }
  oneof _timestamp {
    string timestamp = 5;
  }
  oneof _access_url {
    string access_url = 6;
  }
  oneof _key {
    string key = 7;
  }
  oneof _download_timestamp {
    string download_timestamp = 8;
  }
}
message CloudBackupErrorCode {
  enum Enum {
    BACKUP_OPERATION_IN_PROGRESS = 0;
    BACKUP_CREATION_FAILED = 1;
    BACKUP_CREATION_SUCCEDED = 2;
    BACKUP_UPDATE_FAILED = 3;
    BACKUP_UPDATE_NOT_FOUND = 4;
    BACKUP_UPDATE_SUCCEDED = 5;
    BACKUP_RENAME_FAILED = 6;
    BACKUP_RENAME_NOT_FOUND = 7;
    BACKUP_RENAME_SUCCEDED = 8;
    BACKUP_DOWNLOAD_FAILED = 9;
    BACKUP_DOWNLOAD_NOT_FOUND = 10;
    BACKUP_DOWNLOAD_SUCCEDED = 11;
    BACKUP_DELETE_FAILED = 12;
    BACKUP_DELETE_NOT_FOUND = 13;
    BACKUP_DELETE_SUCCEDED = 14;
    BACKUP_LISTING_FAILED = 15;
    BACKUP_LISTING_SUCCEDED = 16;
    NOT_CONNECTED_OR_LOGGED_IN = 17;
    GRID_NOT_VISIBLE = 18;
  }
}
message CloudBackupMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  repeated cortex_protobuf_v2.CloudBackupItem backups = 3;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _error_code {
    cortex_protobuf_v2.CloudBackupErrorCode.Enum error_code = 4;
  }
  oneof _cloud_error_code {
    int32 cloud_error_code = 5;
  }
  oneof _installation_progress {
    int32 installation_progress = 6;
  }
  oneof _is_busy {
    bool is_busy = 7;
  }
}
message CompilerInhibitedModulesMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _global_gate {
    bool global_gate = 3;
  }
  oneof _global_eq {
    bool global_eq = 4;
  }
}
message SystemTimeSyncMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  uint64 ms_since_epoch = 3;
  oneof _request_id {
    uint64 request_id = 2;
  }
}
message LogsMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _correlation_id {
    string correlation_id = 3;
  }
}
message ProcessDownloadsQueueMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _type {
    int32 type = 3;
  }
}
message CloudTransferStateItem {
  enum State {
    NOT_DOWNLOADED = 0;
    DOWNLOADING = 1;
    DOWNLOADED = 2;
    NOT_UPLOADED = 3;
    UPLOADING = 4;
    UPLOADED = 5;
  }
  string id = 1;
  cortex_protobuf_v2.CloudTransferStateItem.State state = 2;
}
message CloudTransferState {
  repeated cortex_protobuf_v2.CloudTransferStateItem items = 1;
}
message CloudProductMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  repeated int32 to_indices = 6;
  repeated string product_keys = 7;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _type {
    int32 type = 3;
  }
  oneof _from_folder {
    string from_folder = 4;
  }
  oneof _to_folder {
    string to_folder = 5;
  }
  oneof _cloud_transfer_state {
    cortex_protobuf_v2.CloudTransferState cloud_transfer_state = 8;
  }
}
message ConfirmationAction {
  enum Enum {
    OK = 0;
    CANCEL = 1;
  }
}
message ConfirmationMessage {
  uint64 confirmation_id = 2;
  repeated cortex_protobuf_v2.ConfirmationAction.Enum actions = 5;
  oneof _request_id {
    uint64 request_id = 1;
  }
  oneof _title {
    string title = 3;
  }
  oneof _msg {
    string msg = 4;
  }
  oneof _response {
    cortex_protobuf_v2.ConfirmationAction.Enum response = 6;
  }
  oneof _ok_title {
    string ok_title = 7;
  }
  oneof _cancel_title {
    string cancel_title = 8;
  }
}
message SceneColorMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  int32 index = 3;
  uint32 color = 4;
  oneof _request_id {
    uint64 request_id = 2;
  }
}
message ConnectionMessage {
  oneof _request_id {
    uint64 request_id = 1;
  }
  oneof _connected {
    bool connected = 2;
  }
}
message NewModelsMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  repeated uint32 models = 3;
  oneof _request_id {
    uint64 request_id = 2;
  }
}
message ModelRepoMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _model_repo_payload {
    bytes model_repo_payload = 3;
  }
}
message ResetCommsBuffersMessage {
  oneof _request_id {
    uint64 request_id = 1;
  }
  oneof _session_id {
    string session_id = 2;
  }
}
message LicenseItem {
  uint64 plugin_id = 3;
  oneof _id {
    string id = 1;
  }
  oneof _name {
    string name = 2;
  }
  oneof _license_type {
    string license_type = 4;
  }
  oneof _expiration_date {
    string expiration_date = 5;
  }
}
message LicenseMessage {
  enum LicenseUpdateStatus {
    IDLE = 0;
    UPDATING = 1;
    FAILED = 2;
  }
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  repeated cortex_protobuf_v2.LicenseItem licenses = 3;
  repeated uint64 new_plugin_ids = 7;
  repeated uint64 supported_plugin_ids = 8;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _is_enabled {
    bool is_enabled = 4;
  }
  oneof _is_deactivated {
    bool is_deactivated = 5;
  }
  oneof _update_status {
    cortex_protobuf_v2.LicenseMessage.LicenseUpdateStatus update_status = 6;
  }
}
message SuspendConnectionMessage {
  enum Reason {
    BACKUP = 0;
    FACTORY_RESET = 1;
    SETTINGS_RESET = 2;
  }
  oneof _request_id {
    uint64 request_id = 1;
  }
  oneof _suspend {
    bool suspend = 2;
  }
  oneof _reason {
    cortex_protobuf_v2.SuspendConnectionMessage.Reason reason = 3;
  }
}
message GigViewButtonMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  uint64 button_index = 3;
  bool pressed = 4;
  oneof _request_id {
    uint64 request_id = 2;
  }
}
message PinnedModelsMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  repeated uint32 models = 3;
  repeated string captures = 4;
  oneof _request_id {
    uint64 request_id = 2;
  }
}
message GenericErrorMessage {
  enum ErrorCode {
    VERSION_IS_NEWER = 0;
    VERSION_IS_OLDER = 1;
    CLOUD_LOGIN_FAILED = 2;
    EXCESS_DOWNLOADS_PRESETS_WARNING_TRIGGERED = 3;
    EXCESS_DOWNLOADS_CAPTURES_WARNING_TRIGGERED = 4;
  }
  oneof _request_id {
    uint64 request_id = 1;
  }
  oneof _error_code {
    cortex_protobuf_v2.GenericErrorMessage.ErrorCode error_code = 2;
  }
}
message PresetSpeedTestMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _setlist_name {
    string setlist_name = 3;
  }
  oneof _num_laps {
    int32 num_laps = 4;
  }
  oneof _randomize {
    bool randomize = 5;
  }
  oneof _csv_file {
    string csv_file = 6;
  }
}
message UpdaterForwardRequestType {
  enum Enum {
    CHECK = 0;
    DOWNLOAD_CHANGELOG = 1;
    DOWNLOAD_UPDATE_HEADER = 2;
    DOWNLOAD_UPDATE = 3;
  }
}
message UpdaterForwardRequest {
  cortex_protobuf_v2.UpdaterForwardRequestType.Enum type = 1;
  string url = 2;
  int32 timeout = 3;
  repeated cortex_protobuf_v2.ProductForwardHeaderPair headers = 5;
  oneof _payload {
    string payload = 4;
  }
}
message UpdaterForwardResponse {
  bytes payload = 1;
  oneof _is_last_chunk {
    bool is_last_chunk = 2;
  }
  oneof _error_code {
    int32 error_code = 3;
  }
}
message UpdaterForwardMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  uint64 updater_request_id = 3;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _request {
    cortex_protobuf_v2.UpdaterForwardRequest request = 4;
  }
  oneof _response {
    cortex_protobuf_v2.UpdaterForwardResponse response = 5;
  }
}
message UpdaterCommand {
  enum Enum {
    CHECK = 0;
    CHECK_AND_DOWNLOAD = 1;
    INSTALL = 2;
    RESTART_DOWNLOAD_VIA_CONTROL = 3;
    CANCEL_DOWNLOAD = 4;
  }
}
message UpdaterStatus {
  enum Enum {
    NONE = 0;
    NEW_VERSION_AVAILABLE_TO_DOWNLOAD = 1;
    NEW_VERSION_DOWNLOADED = 2;
    NO_NEW_VERSION_AVAILABLE = 3;
  }
}
message UpdaterState {
  enum Enum {
    IDLE = 0;
    REQUESTING_DATA = 1;
    DOWNLOADING_DATA = 2;
    UPDATING = 3;
    REBOOT = 4;
    FAILED = 5;
  }
}
message UpdaterMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _command {
    cortex_protobuf_v2.UpdaterCommand.Enum command = 3;
  }
  oneof _status {
    cortex_protobuf_v2.UpdaterStatus.Enum status = 4;
  }
  oneof _state {
    cortex_protobuf_v2.UpdaterState.Enum state = 5;
  }
  oneof _new_version_id {
    string new_version_id = 6;
  }
  oneof _changelog {
    string changelog = 7;
  }
  oneof _download_progress {
    float download_progress = 8;
  }
  oneof _installation_progress {
    float installation_progress = 9;
  }
}
message GainCalParameter {
  enum GainCalibrationOutput {
    OUT_1_GAIN = 0;
    OUT_2_GAIN = 1;
    OUT_3_GAIN = 2;
    OUT_4_GAIN = 3;
    SEND_1 = 4;
    SEND_2 = 5;
    HP_L_GAIN = 6;
    HP_R_GAIN = 7;
  }
  cortex_protobuf_v2.GainCalParameter.GainCalibrationOutput index = 1;
  float gain_db = 2;
}
message GainCalInputPortParameter {
  enum InputPortId {
    EMPTY = 0;
    INPUT_1 = 1;
    INPUT_2 = 2;
    INPUT_1_2 = 3;
    RETURN_1 = 4;
    RETURN_2 = 5;
    RETURN_1_2 = 6;
    PREV_ROW = 7;
    USB_IN_5 = 8;
    USB_IN_6 = 9;
    USB_IN_7 = 10;
    USB_IN_8 = 11;
    USB_IN_5_6 = 12;
    USB_IN_7_8 = 13;
    SIDECHAIN_BUFFER = 14;
    MAX_PORTS = 15;
  }
  cortex_protobuf_v2.GainCalInputPortParameter.InputPortId port_id = 1;
  float level = 2;
}
message GainCalOutputPortParameter {
  enum OutputPortId {
    EMPTY = 0;
    XLR_1_2 = 1;
    OUTPUT_3_4 = 2;
    SEND_1_2 = 3;
    XLR_1 = 4;
    XLR_2 = 5;
    OUTPUT_3 = 6;
    OUTPUT_4 = 7;
    SEND_1 = 8;
    SEND_2 = 9;
    USB_OUT_5 = 10;
    USB_OUT_6 = 11;
    USB_OUT_7 = 12;
    USB_OUT_8 = 13;
    USB_OUT_5_6 = 14;
    USB_OUT_7_8 = 15;
    NEXT_ROW_3 = 16;
    NEXT_ROW_4 = 17;
    NEXT_ROW_3_4 = 18;
    MULTIPLE_OUTS = 19;
    USB_OUT_3 = 20;
    USB_OUT_4 = 21;
    USB_OUT_3_4 = 22;
    MAX_PORTS = 23;
  }
  cortex_protobuf_v2.GainCalOutputPortParameter.OutputPortId port_id = 1;
  float level = 2;
}
message GainCalHeadphonesFeed {
  float level = 1;
  cortex_protobuf_v2.GainCalOutputPortParameter.OutputPortId output_port_id = 2;
}
message GainCalHeadphonesParameter {
  oneof _level {
    float level = 1;
  }
  oneof _feed {
    cortex_protobuf_v2.GainCalHeadphonesFeed feed = 2;
  }
}
message GainCalibrationMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  repeated cortex_protobuf_v2.GainCalParameter gains = 3;
  repeated cortex_protobuf_v2.GainCalInputPortParameter in_port = 6;
  repeated cortex_protobuf_v2.GainCalOutputPortParameter out_port = 7;
  repeated cortex_protobuf_v2.GainCalHeadphonesParameter hp_port = 8;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _load_input_preset {
    bool load_input_preset = 4;
  }
  oneof _load_output_preset {
    bool load_output_preset = 5;
  }
}
message SerializationMessage {
  enum Result {
    SUCCESS = 0;
    IS_SERIALIZED = 1;
  }
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _serial_number {
    string serial_number = 3;
  }
  oneof _display_type {
    string display_type = 4;
  }
  oneof _result {
    cortex_protobuf_v2.SerializationMessage.Result result = 5;
  }
}
message TestFarmTestState {
  enum Enum {
    NONE = 0;
    QUEUED = 1;
    RUNNING = 2;
    PASSED = 3;
    FAILED = 4;
    ABORTING = 5;
    ABORTED = 6;
  }
}
message TestFarmMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  string test_id = 3;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _state {
    cortex_protobuf_v2.TestFarmTestState.Enum state = 4;
  }
}
message NeuralCapture2Message {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  repeated cortex_protobuf_v2.NeuralCaptureParameter parameters = 6;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _state {
    int32 state = 3;
  }
  oneof _job_id {
    string job_id = 4;
  }
  oneof _save_info {
    cortex_protobuf_v2.NeuralCaptureSaveInfo save_info = 5;
  }
  oneof _cabsim_bypass {
    bool cabsim_bypass = 7;
  }
  oneof _cabsim {
    Model cabsim = 8;
  }
  oneof _error_id {
    int32 error_id = 9;
  }
  oneof _error_string {
    string error_string = 10;
  }
  oneof _open_dialog {
    bool open_dialog = 11;
  }
  oneof _start_from_scratch {
    bool start_from_scratch = 12;
  }
}
message ProductionTestMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _led_color {
    uint32 led_color = 3;
  }
  oneof _enable_tempo_led {
    bool enable_tempo_led = 4;
  }
}
message LoadAutomatedTestPresetMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  oneof _request_id {
    uint64 request_id = 2;
  }
}
message SetTestPresetInputOutputPortsMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  repeated cortex_protobuf_v2.GainCalInputPortParameter.InputPortId input_ports = 3;
  repeated cortex_protobuf_v2.GainCalOutputPortParameter.OutputPortId output_ports = 4;
  repeated uint32 input_port_rows = 5;
  repeated uint32 output_port_rows = 6;
  oneof _request_id {
    uint64 request_id = 2;
  }
}
message SetTestPresetSplitMixPointsMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  repeated uint32 split_mix_rows = 3;
  repeated int32 split_points = 4;
  repeated int32 mix_points = 5;
  repeated bool hard_pan_mixer = 6;
  oneof _request_id {
    uint64 request_id = 2;
  }
}
message GenerateTestPresetMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  oneof _request_id {
    uint64 request_id = 2;
  }
  oneof _latency_test_mode {
    uint32 latency_test_mode = 3;
  }
  oneof _grid_density {
    uint32 grid_density = 4;
  }
}

message ModelPresetID {
  optional string value = 1;
  optional bool is_factory = 2;
  optional uint32 hash = 3;
}

message ModelPreset {
  optional cortex_protobuf_v2.ModelPresetID id = 1;
  optional string name = 2;
  optional bool is_default = 3;
  optional Model model = 4;
}

message ModelPresetMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  optional uint64 request_id = 2;
  repeated cortex_protobuf_v2.ModelPreset presets = 3;
  optional int32 create_from_row = 4;
  optional int32 create_from_column = 5;
  optional int32 create_from_hash = 6;
  optional int32 loaded_row = 7;
  optional int32 loaded_column = 8;
  optional int32 loaded_hash = 9;
  optional int32 loaded_capture_version = 10;
  optional cortex_protobuf_v2.ModelPresetID loaded_preset_id = 11;
}

message RemoteControlMouse {
  float x = 1;
  float y = 2;
  enum Type {
    PRESS = 0;
    RELEASE = 1;
    MOVE = 2;
    TAP = 3;
    DRAG = 4;
  }
  Type type = 3;
  float to_x = 4;
  float to_y = 5;
}

message RemoteControlScreenshot {
  optional bytes payload = 1;
  optional uint32 x = 2;
  optional uint32 y = 3;
  optional uint32 w = 4;
  optional uint32 h = 5;
}

message RemoteControlGraphicsTree {
  optional string payload = 1;
}

message RemoteControlMessage {
  cortex_protobuf_v2.MessageAction.Enum action = 1;
  optional uint64 request_id = 2;
  optional cortex_protobuf_v2.RemoteControlMouse mouse = 3;
  optional cortex_protobuf_v2.RemoteControlScreenshot screenshot = 4;
  optional cortex_protobuf_v2.RemoteControlGraphicsTree graphics_tree = 5;
}

