#!/usr/bin/env python3
"""Generate ``pyquadcortex/protocol/models.py`` - constants for the FACTORY blocks.

A block is stored on the wire as an integer model id. Ids for factory content
are the same on every Quad Cortex, so they can be constants a caller writes
against directly. Ids for anything else cannot: purchased plugin models may be
absent, and Neural Capture ids are user slots that mean different things on
different units. Those must be resolved at runtime via ``qc.catalog``, so this
generator emits only ``Model.is_factory`` entries.

Source: a device's ModelRepo payload, either live or previously saved.

    # from a connected Quad Cortex (Cortex Control must be quit)
    python scripts/generate_models.py

    # from a saved payload, for reproducible regeneration
    python scripts/generate_models.py --payload model_repo_payload.bin

Only identifiers and integers are emitted - no descriptions and no "Based on"
attribution text.
"""

import argparse
import keyword
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

from pyquadcortex.protocol import catalog  # noqa: E402

OUTPUT = (pathlib.Path(__file__).resolve().parents[1]
          / "pyquadcortex" / "protocol" / "models.py")


def class_name(category: str) -> str:
    """'Cabsim Bass (M)' -> 'CabsimBassM'."""
    cleaned = re.sub(r"[^0-9a-zA-Z ]+", " ", category)
    name = "".join(word[:1].upper() + word[1:] for word in cleaned.split())
    return name or "Uncategorized"


def const_name(model: str) -> str:
    """'810 Amped VT Aln 70s (M)' -> 'N810_AMPED_VT_ALN_70S_M'."""
    cleaned = re.sub(r"[^0-9a-zA-Z]+", "_", model).strip("_").upper()
    if not cleaned:
        cleaned = "UNNAMED"
    if cleaned[0].isdigit():
        cleaned = "N" + cleaned            # identifiers cannot start with a digit
    if keyword.iskeyword(cleaned.lower()):
        cleaned += "_"
    return cleaned


def render(cat: catalog.ModelCatalog) -> str:
    by_category: dict[str, list[catalog.Model]] = {}
    for model in cat.factory_models():
        by_category.setdefault(model.category, []).append(model)

    lines = [
        '"""Constants for the factory blocks every Quad Cortex has.',
        "",
        "GENERATED by scripts/generate_models.py - do not edit by hand.",
        "",
        "Each class is a model category and each constant a block's wire id, so a",
        "constant can be passed straight to :meth:`pyquadcortex.protocol.QuadCortex.set_block`::",
        "",
        "    qc.set_block(Block(0, 2, models.GuitarOverdrive.CHIEF_DS1))",
        "",
        "Only FACTORY content is here. Purchased plugin models and Neural Captures",
        "are omitted on purpose: a unit may not have them, and capture ids are user",
        "slots that differ per device. Resolve those at runtime instead::",
        "",
        "    qc.catalog.find('My Capture').id",
        "",
        "Names that begin with a digit are prefixed with N (810 -> N810).",
        '"""',
        "",
    ]

    all_entries: list[tuple[str, int]] = []
    for category in sorted(by_category):
        cls = class_name(category)
        lines.append("")
        lines.append(f"class {cls}:")
        lines.append(f'    """{category}."""')
        lines.append("")
        used: dict[str, int] = {}
        # Current models are named first so they win the clean identifier; a
        # superseded model with the same display name (there are two "Graphic-9"
        # equalizers) then takes a _LEGACY suffix instead of the bare name.
        ordered = sorted(by_category[category], key=lambda m: (m.superseded, m.id))
        for model in ordered:
            name = const_name(model.name)
            if model.superseded:
                name = f"{name}_LEGACY"
            if name in used:                # still ambiguous: fall back to the id
                name = f"{name}_{model.id}"
            used[name] = model.id
            lines.append(f"    {name} = {model.id}")
            all_entries.append((f"{cls}.{name}", model.id))
        lines.append("")

    lines.append("")
    lines.append("#: Every generated constant, as 'Category.NAME' -> wire id.")
    lines.append("ALL = {")
    for qualified, model_id in all_entries:
        lines.append(f'    "{qualified}": {model_id},')
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def load_payload(path: str | None) -> bytes:
    if path:
        return pathlib.Path(path).read_bytes()
    import pyquadcortex

    with pyquadcortex.protocol.connect() as qc:
        return qc._fetch_model_repo()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--payload", help="a saved ModelRepo payload; omit to read a device")
    parser.add_argument("--out", default=str(OUTPUT), help=f"output path (default {OUTPUT})")
    args = parser.parse_args()

    cat = catalog.parse_model_repo(load_payload(args.payload))
    factory = cat.factory_models()
    source = render(cat)
    pathlib.Path(args.out).write_text(source, encoding="utf-8")
    print(f"wrote {args.out}: {len(factory)} factory models "
          f"of {len(cat)} total, {len({m.category for m in factory})} categories")
    return 0


if __name__ == "__main__":
    sys.exit(main())
