"""The choices a list-valued parameter offers, as enums.

GENERATED by ``scripts/generate_options.py``. Do not edit by hand.

A list parameter stores ``index / (count - 1)`` on the wire, so picking
an option means knowing its position. These name the positions::

    qc.set_param_option(block, 'DYN MODE', options.DynMode.GATE)

148 enums cover 365 parameters, because the same list means
the same thing wherever it appears - the note-length list is shared by
``SYNC NOTE``, ``SYNC NOTE L``, ``SYNC NOTE R`` and two more.

**A two-option Off/On parameter gets no enum.** 247 parameters offer
exactly those, and ``True`` says everything ``OffOn.ON`` would::

    qc.set_param(block, 'SYNC', True)

**A dynamic list gets no enum either.** Twelve parameters build their
list from the preset - it includes one entry per upstream block - so
read those with :func:`~pyquadcortex.protocol.client.param_options`.

The member names are ours; the wire's strings are the device's, and
``OPTION_LABELS`` keeps them verbatim. Where the two differ the label is
in a comment beside the member.
"""
from enum import IntEnum


class Adjust(IntEnum):
    """2 parameters use this list: Ø ADJUST, Ø ADJUST R

    On Phase Doctor.
    """

    BYPASS = 0
    N90 = 1    # '90°'
    N180 = 2    # '180°'


class AnalogDelayMSyncNote(IntEnum):
    """2 parameters use this list: SYNC NOTE

    On Analog Delay (M), Analog Delay (ST).
    """

    N1_16 = 0    # '1/16'
    N1_8T = 1    # '1/8T'
    N1_16D = 2    # '1/16D'
    N1_8 = 3    # '1/8'
    N1_4T = 4    # '1/4T'
    N1_8D = 5    # '1/8D'
    N1_4 = 6    # '1/4'
    N1_2T = 7    # '1/2T'
    N1_4D = 8    # '1/4D'
    N1_2 = 9    # '1/2'
    N1_1T = 10    # '1/1T'
    N1_2D = 11    # '1/2D'
    N1_1 = 12    # '1/1'


class ArpPattern(IntEnum):
    """1 parameter use this list: ARP PATTERN

    On Overlord Synth.
    """

    UP = 0
    DOWN = 1
    UP_AND_DOWN = 2    # 'Up & Down'
    DOWN_AND_UP = 3    # 'Down & Up'
    RANDOM = 4


class AutoSpeed(IntEnum):
    """1 parameter use this list: AUTO SPEED

    On Misha Modulator.
    """

    N1_1 = 0    # '1/1'
    N1_2 = 1    # '1/2'
    N1_4 = 2    # '1/4'
    N1_8 = 3    # '1/8'
    N1_16 = 4    # '1/16'
    N1_32 = 5    # '1/32'


class BitDepth(IntEnum):
    """2 parameters use this list: BIT DEPTH

    On Bit-Crusher (ST), Bit-Crusher Engine (M).
    """

    N1 = 0    # '1'
    N2 = 1    # '2'
    N3 = 2    # '3'
    N4 = 3    # '4'
    N5 = 4    # '5'
    N6 = 5    # '6'
    N7 = 6    # '7'
    N8 = 7    # '8'
    N9 = 8    # '9'
    N10 = 9    # '10'
    N11 = 10    # '11'
    N12 = 11    # '12'
    N13 = 12    # '13'
    N14 = 13    # '14'
    N15 = 14    # '15'
    N16 = 15    # '16'


class Boost(IntEnum):
    """2 parameters use this list: BOOST

    On UK C15 TopBoost, UK C30 TopBoost.
    """

    HOT = 0
    COOL = 1


class Bright(IntEnum):
    """1 parameter use this list: BRIGHT

    On Freeman 100 Clean.
    """

    NORMAL = 0
    BRIGHT_1 = 1    # 'Bright 1'
    BRIGHT_2 = 2    # 'Bright 2'


class Center(IntEnum):
    """2 parameters use this list: Ø CENTER, Ø CENTER R

    On Phase Doctor.
    """

    LO_FREQ = 0    # 'Lo Freq'
    HI_FREQ = 1    # 'Hi Freq'


class ChannelNormal(IntEnum):
    """1 parameter use this list: CHANNEL

    On Soldano SLO-100®.
    """

    NORMAL = 0
    OD = 1


class ChiefCe2wMType(IntEnum):
    """2 parameters use this list: TYPE

    On Chief CE2W (M), Chief CE2W (ST).
    """

    CE2_C = 0    # 'CE2-C'
    CE1_C = 1    # 'CE1-C'
    CE1_V = 2    # 'CE1-V'


class ChiefDc2wMMode(IntEnum):
    """2 parameters use this list: MODE

    On Chief DC2W (M), Chief DC2W (ST).
    """

    N1 = 0    # '1'
    N2 = 1    # '2'
    N3 = 2    # '3'
    N4 = 3    # '4'
    N1_2 = 4    # '1+2'
    N1_3 = 5    # '1+3'
    N1_4 = 6    # '1+4'
    N2_3 = 7    # '2+3'
    N2_4 = 8    # '2+4'
    N3_4 = 9    # '3+4'


class ChiefDc2wMType(IntEnum):
    """2 parameters use this list: TYPE

    On Chief DC2W (M), Chief DC2W (ST).
    """

    S = 0
    SDD_320 = 1    # 'SDD-320'


class Color(IntEnum):
    """1 parameter use this list: COLOR

    On Flanger Engine.
    """

    NATURAL = 0
    WARM = 1
    DARK = 2
    BRIGHT = 3
    SPARKLE = 4
    DUSTY = 5
    SPIKY = 6
    TWANGY = 7


class CoryWongDIFunkConsoleAttack(IntEnum):
    """1 parameter use this list: ATTACK

    On Cory Wong D.I. Funk Console.
    """

    FAST = 0
    SLOW = 1


class Crunch(IntEnum):
    """1 parameter use this list: CRUNCH

    On Soldano SLO-100®.
    """

    CLEAN = 0
    CRUNCH = 1


class Curve(IntEnum):
    """1 parameter use this list: CURVE

    On Volume.
    """

    LINEAR = 0
    LOG = 1


class DCellHisbertCh2Mode(IntEnum):
    """1 parameter use this list: MODE

    On D-Cell Hisbert Ch2.
    """

    MINUS = 0    # '-'
    PLUS = 1    # '+'


class Decay(IntEnum):
    """1 parameter use this list: DECAY

    On Foog.
    """

    FAST = 0
    SMOOTH = 1


class DigitalFlangerPolarity(IntEnum):
    """1 parameter use this list: POLARITY

    On Digital Flanger.
    """

    NEG = 0
    POS = 1


class DivSource(IntEnum):
    """1 parameter use this list: DIV. SOURCE

    On Phase-Locked Loop.
    """

    UNISON = 0
    MULTIPLIER = 1


class Divider(IntEnum):
    """1 parameter use this list: DIVIDER

    On Phase-Locked Loop.
    """

    N2 = 0    # '2'
    N3 = 1    # '3'
    N4 = 2    # '4'
    N5 = 3    # '5'
    N6 = 4    # '6'
    N7 = 5    # '7'
    N8 = 6    # '8'


class DoublerInput(IntEnum):
    """2 parameters use this list: INPUT

    On Doubler, Plugin Doubler.
    """

    LEFT = 0
    MONO = 1
    RIGHT = 2


class DreamChorusMMode(IntEnum):
    """2 parameters use this list: MODE

    On Dream Chorus (M), Dream Chorus (ST).
    """

    CHO1 = 0
    CHO2 = 1


class DriveType(IntEnum):
    """2 parameters use this list: DRIVE TYPE

    On Chorus Engine, Flanger Engine.
    """

    SOFT = 0
    EDGY = 1
    HARD = 2
    OFF = 3


class DualChorusMode(IntEnum):
    """1 parameter use this list: MODE

    On Dual Chorus.
    """

    CHORUS = 0
    VIBE = 1


class DumbbellOdsChannel(IntEnum):
    """1 parameter use this list: CHANNEL

    On Dumbbell ODS.
    """

    CLEAN = 0
    OD = 1


class DumbbellOdsEq(IntEnum):
    """1 parameter use this list: EQ

    On Dumbbell ODS.
    """

    JAZZ = 0
    ROCK = 1


class DuplicateMode(IntEnum):
    """1 parameter use this list: DUPLICATE MODE

    On Looper X.
    """

    FREE = 0
    SYNC = 1


class DynMode2(IntEnum):
    """9 parameters use this list: DYN MODE

    On 9 models, among them Gojira DLY, Nameless Delay, Nolly Delay-1 (M).
    """

    DUCK = 0
    GATE = 1


class DynMode3(IntEnum):
    """12 parameters use this list: DYN MODE

    On 12 models, among them Analog Delay (M), Analog Delay (ST), Digital Delay (M).
    """

    OFF = 0
    DUCK = 1
    GATE = 2


class Eq3(IntEnum):
    """8 parameters use this list: EQ

    On 8 models, among them CA 1Star Clean 100W Normal, CA 1Star Clean 100W Tweed, CA 1Star Clean 50W Normal.
    """

    NORMAL = 0
    THICK = 1
    THICKER = 2


class FeedbackMode(IntEnum):
    """2 parameters use this list: FEEDBACK MODE

    On Dual Reverse Delay, Reverse Delay (M).
    """

    REVERSE = 0
    FLIP = 1


class Filter(IntEnum):
    """1 parameter use this list: FILTER

    On Foog.
    """

    N4_POLE = 0    # '4-POLE'
    N2_POLE = 1    # '2-POLE'


class FilterCutoff(IntEnum):
    """1 parameter use this list: FILTER CUTOFF

    On Love Meat.
    """

    LOW = 0
    A = 1
    B = 2
    HIGH = 3


class FilterType(IntEnum):
    """1 parameter use this list: FILTER TYPE

    On Love Meat.
    """

    LOWPASS = 0
    BANDPASS = 1
    HIGHPASS = 2


class FlangerEngineWaveform(IntEnum):
    """1 parameter use this list: WAVEFORM

    On Flanger Engine.
    """

    SINE = 0
    TRIANGLE = 1
    SQUARE = 2
    SAW_UP = 3    # 'Saw Up'
    SAW_DN = 4    # 'Saw Dn'
    RNDSMOOTH = 5
    RNDSTEP = 6


class Focus(IntEnum):
    """2 parameters use this list: FOCUS

    On Victor Squid Ch1, Victor Squid Ch2.
    """

    ON = 0
    OFF = 1


class Freeze(IntEnum):
    """3 parameters use this list: FREEZE, ON / OFF

    On Freeze, Rabea Aeons Reverb, Vintage Digital.
    """

    RELEASE = 0
    FREEZE = 1


class Frequency(IntEnum):
    """2 parameters use this list: FREQUENCY, UNI. AMOUNT

    On Amped Super Valve, Overlord Synth.
    """

    N1 = 0    # '1'
    N2 = 1    # '2'
    N3 = 2    # '3'
    N4 = 3    # '4'
    N5 = 4    # '5'


class GOccurrence(IntEnum):
    """1 parameter use this list: G. OCCURRENCE

    On Glitch.
    """

    N1_4 = 0    # '1/4'
    N1_8 = 1    # '1/8'
    N1_16 = 2    # '1/16'
    N1_32 = 3    # '1/32'


class GainPolarity(IntEnum):
    """3 parameters use this list: PHASE INVERT, Ø POLARITY, Ø POLARITY R

    On Gain, Phase Doctor.
    """

    NORMAL = 0
    INVERTED = 1


class GlitchMode(IntEnum):
    """1 parameter use this list: MODE

    On Glitch.
    """

    SEQUENCE = 0
    PITCH_DELAY = 1    # 'Pitch Delay'
    INTERFERE = 2
    TEXTURIZER = 3


class GojiraWowMode(IntEnum):
    """1 parameter use this list: MODE

    On Gojira WOW.
    """

    BLADE_2 = 0    # 'Blade 2'
    BLADE_1 = 1    # 'Blade 1'
    FATSO = 2


class GrainLength(IntEnum):
    """1 parameter use this list: GRAIN LENGTH

    On Glitch.
    """

    N1_64 = 0    # '1/64'
    N1_32 = 1    # '1/32'
    N1_16 = 2    # '1/16'
    N1_8 = 3    # '1/8'
    N1_4 = 4    # '1/4'
    N1_2 = 5    # '1/2'
    N1_1 = 6    # '1/1'


class HighsFreq(IntEnum):
    """1 parameter use this list: HIGHS FREQ

    On Cory Wong D.I. Funk Console.
    """

    N4_KHZ = 0    # '4 kHz'
    N2_5_KHZ = 1    # '2.5 kHz'


class HorizonDevicesPrecisionDriveAttack(IntEnum):
    """1 parameter use this list: ATTACK

    On Horizon Devices® Precision Drive™.
    """

    N470 = 0    # '470'
    N330 = 1    # '330'
    N100 = 2    # '100'
    N68 = 3    # '68'
    N47 = 4    # '47'
    N33 = 5    # '33'


class HpfSlope(IntEnum):
    """2 parameters use this list: HPF SLOPE, LPF SLOPE

    On Low-High Cut.
    """

    FLAT = 0
    MINUS_6 = 1    # '-6'
    MINUS_12 = 2    # '-12'
    MINUS_18 = 3    # '-18'
    MINUS_24 = 4    # '-24'
    MINUS_30 = 5    # '-30'
    MINUS_36 = 6    # '-36'
    MINUS_42 = 7    # '-42'
    MINUS_48 = 8    # '-48'


class Instrument(IntEnum):
    """1 parameter use this list: INSTRUMENT

    On Phase-Locked Loop.
    """

    GUITAR = 0
    BASS = 1


class Invert(IntEnum):
    """16 parameters use this list: INVERT

    On 8 models, among them Dual (M), Dual (M) Lite, Dual (ST).
    """

    NORMAL = 0    # 'Noral'
    INVERTED = 1


class JohnMayerHeadroomHeroInput(IntEnum):
    """1 parameter use this list: INPUT

    On John Mayer Headroom Hero.
    """

    NORMAL = 0
    FET = 1


class JohnMayerSignature83Eq(IntEnum):
    """1 parameter use this list: EQ

    On John Mayer Signature 83.
    """

    EQ1 = 0
    EQ2 = 1


class Key(IntEnum):
    """4 parameters use this list: KEY, ROOT

    On 4 models, among them Arpeggio Delay, Minivoicer, Multivoicer.
    """

    A = 0
    A_1 = 1    # 'A#'
    B = 2
    C = 3
    C_4 = 4    # 'C#'
    D = 5
    D_6 = 6    # 'D#'
    E = 7
    F = 8
    F_9 = 9    # 'F#'
    G = 10
    G_11 = 11    # 'G#'


class LoopLength(IntEnum):
    """1 parameter use this list: LOOP LENGTH

    On Glitch.
    """

    N1_2_BAR = 0    # '1/2 BAR'
    N1_BAR = 1    # '1 BAR'
    N2_BARS = 2    # '2 BARS'
    N4_BARS = 3    # '4 BARS'


class LowsFreq(IntEnum):
    """1 parameter use this list: LOWS FREQ

    On Cory Wong D.I. Funk Console.
    """

    N225_HZ = 0    # '225 Hz'
    N150_HZ = 1    # '150 Hz'


class M(IntEnum):
    """1 parameter use this list: M

    On Misha Laser.
    """

    RING = 0
    PITCH = 1


class Mid(IntEnum):
    """3 parameters use this list: BRIGHT, MID, PREAMP

    On Dumbbell ODS.
    """

    OFF = 0
    BOOST = 1


class MidsFreq(IntEnum):
    """1 parameter use this list: MIDS FREQ

    On Cory Wong D.I. Funk Console.
    """

    N900_HZ = 0    # '900 Hz'
    N600_HZ = 1    # '600 Hz'


class MinivoicerMidiCh(IntEnum):
    """1 parameter use this list: MIDI CH

    On Minivoicer.
    """

    N1 = 0    # '1'
    N2 = 1    # '2'
    N3 = 2    # '3'
    N4 = 3    # '4'
    N5 = 4    # '5'
    N6 = 5    # '6'
    N7 = 6    # '7'
    N8 = 7    # '8'
    N9 = 8    # '9'
    N10 = 9    # '10'
    N11 = 10    # '11'
    N12 = 11    # '12'
    N13 = 12    # '13'
    N14 = 13    # '14'
    N15 = 14    # '15'
    N16 = 15    # '16'
    OMNI = 16


class MinivoicerMode(IntEnum):
    """2 parameters use this list: MODE

    On Minivoicer, Pitch Correction.
    """

    MAJOR = 0
    HARMONIC_MINOR = 1    # 'Harmonic Minor'
    NATURAL_MINOR = 2    # 'Natural Minor'
    MELODIC_MINOR = 3    # 'Melodic Minor'
    CHROMATIC = 4


class MinivoicerV1Interval(IntEnum):
    """2 parameters use this list: V1 INTERVAL, V2 INTERVAL

    On Minivoicer.
    """

    MINUS_15TH = 0    # '-15th'
    MINUS_14TH = 1    # '-14th'
    MINUS_13TH = 2    # '-13th'
    MINUS_12TH = 3    # '-12th'
    MINUS_11TH = 4    # '-11th'
    MINUS_10TH = 5    # '-10th'
    MINUS_9TH = 6    # '-9th'
    MINUS_8TH = 7    # '-8th'
    MINUS_7TH = 8    # '-7th'
    MINUS_6TH = 9    # '-6th'
    MINUS_5TH = 10    # '-5th'
    MINUS_4TH = 11    # '-4th'
    MINUS_3RD = 12    # '-3rd'
    MINUS_2ND = 13    # '-2nd'
    ROOT = 14
    N2ND = 15    # '2nd'
    N3RD = 16    # '3rd'
    N4TH = 17    # '4th'
    N5TH = 18    # '5th'
    N6TH = 19    # '6th'
    N7TH = 20    # '7th'
    N8TH = 21    # '8th'
    N9TH = 22    # '9th'
    N10TH = 23    # '10th'
    N11TH = 24    # '11th'
    N12TH = 25    # '12th'
    N13TH = 26    # '13th'
    N14TH = 27    # '14th'
    N15TH = 28    # '15th'


class MishaLaserMode(IntEnum):
    """1 parameter use this list: MODE

    On Misha Laser.
    """

    PEDAL = 0
    ENVELOPE = 1


class MishaModulatorMode(IntEnum):
    """1 parameter use this list: MODE

    On Misha Modulator.
    """

    CHORUS = 0
    FLANGER = 1


class MishaRhythmInput(IntEnum):
    """3 parameters use this list: INPUT, VOICE

    On Misha Rhythm, US DLX 64 Vintage, US DLX 65 Reissue.
    """

    LOW = 0
    HIGH = 1


class MishaStereoDelayMode(IntEnum):
    """1 parameter use this list: MODE

    On Misha Stereo Delay.
    """

    STEREO = 0
    PHASE_INV = 1    # 'Phase Inv'
    PING_PONG = 2    # 'Ping Pong'


class MixLaw(IntEnum):
    """7 parameters use this list: MIX LAW

    On 7 models, among them Cory Wong The Wash, Default Reverb, Gojira REV.
    """

    NOLLY = 0
    NOLLYSKEWED = 1
    NOLLYSKEWEDPLUG = 2


class ModSource(IntEnum):
    """1 parameter use this list: MOD SOURCE

    On Micro Processor (ST).
    """

    LFO = 0
    LFO_STEREO = 1    # 'LFO Stereo'
    PLUS_ENVELOPE = 2    # '+Envelope'
    MINUS_ENVELOPE = 3    # '-Envelope'


class Mode2(IntEnum):
    """4 parameters use this list: MODE

    On 4 models, among them Cory Wong Delay-y-y, Crystal Delay, Petrucci Delay.
    """

    SINGLE = 0
    DUAL = 1


class Model(IntEnum):
    """1 parameter use this list: MODEL

    On John Mayer Tealbreaker.
    """

    TS = 0
    BB = 1


class MulSource(IntEnum):
    """1 parameter use this list: MUL. SOURCE

    On Phase-Locked Loop.
    """

    UNISON = 0
    MINUS_1_OCTAVE = 1    # '-1 Octave'
    MINUS_2_OCTAVES = 2    # '-2 Octaves'


class MultivoicerMidiCh(IntEnum):
    """2 parameters use this list: MIDI CH, MIDI CH.

    On Multivoicer, Overlord Synth.
    """

    OFF = 0
    N1 = 1    # '1'
    N2 = 2    # '2'
    N3 = 3    # '3'
    N4 = 4    # '4'
    N5 = 5    # '5'
    N6 = 6    # '6'
    N7 = 7    # '7'
    N8 = 8    # '8'
    N9 = 9    # '9'
    N10 = 10    # '10'
    N11 = 11    # '11'
    N12 = 12    # '12'
    N13 = 13    # '13'
    N14 = 14    # '14'
    N15 = 15    # '15'
    N16 = 16    # '16'
    OMNI = 17


class MultivoicerScale(IntEnum):
    """2 parameters use this list: SCALE

    On Arpeggio Delay, Multivoicer.
    """

    CHROMATIC = 0
    MAJOR = 1
    NATURAL_MINOR = 2    # 'Natural Minor'
    HARMONIC_MINOR = 3    # 'Harmonic Minor'
    MELODIC_MINOR = 4    # 'Melodic Minor'


class MultivoicerV1Interval(IntEnum):
    """4 parameters use this list: V1 INTERVAL, V2 INTERVAL, V3 INTERVAL, V4 INTERVAL

    On Multivoicer.
    """

    MINUS_15TH = 0    # '-15th'
    MINUS_14TH = 1    # '-14th'
    MINUS_13TH = 2    # '-13th'
    MINUS_12TH = 3    # '-12th'
    MINUS_11TH = 4    # '-11th'
    MINUS_10TH = 5    # '-10th'
    MINUS_9TH = 6    # '-9th'
    MINUS_8TH = 7    # '-8th'
    MINUS_7TH = 8    # '-7th'
    MINUS_6TH = 9    # '-6th'
    MINUS_5TH = 10    # '-5th'
    MINUS_4TH = 11    # '-4th'
    MINUS_3RD = 12    # '-3rd'
    MINUS_2ND = 13    # '-2nd'
    ROOT = 14
    PLUS_2ND = 15    # '+2nd'
    PLUS_3RD = 16    # '+3rd'
    PLUS_4TH = 17    # '+4th'
    PLUS_5TH = 18    # '+5th'
    PLUS_6TH = 19    # '+6th'
    PLUS_7TH = 20    # '+7th'
    PLUS_8TH = 21    # '+8th'
    PLUS_9TH = 22    # '+9th'
    PLUS_10TH = 23    # '+10th'
    PLUS_11TH = 24    # '+11th'
    PLUS_12TH = 25    # '+12th'
    PLUS_13TH = 26    # '+13th'
    PLUS_14TH = 27    # '+14th'
    PLUS_15TH = 28    # '+15th'


class MxPhase95Mode(IntEnum):
    """1 parameter use this list: MODE

    On MX Phase 95.
    """

    BLOCK = 0
    SCRIPT = 1


class MxPhase95Type(IntEnum):
    """1 parameter use this list: TYPE

    On MX Phase 95.
    """

    N90 = 0    # '90'
    N45 = 1    # '45'


class NollyCompressorAttack(IntEnum):
    """1 parameter use this list: ATTACK

    On Nolly Compressor.
    """

    SMOOTH = 0
    SNAPPY = 1


class Notelength(IntEnum):
    """1 parameter use this list: NOTELENGTH

    On TempoControl.
    """

    QUARTER = 0
    EIGHTH = 1
    TRIPLET = 2
    SIXTEENTH = 3


class Octave(IntEnum):
    """1 parameter use this list: OCTAVE

    On Overlord Synth.
    """

    MINUS_2 = 0    # '-2'
    MINUS_1 = 1    # '-1'
    N0 = 2    # '0'
    N1 = 3    # '1'
    N2 = 4    # '2'


class Osc1Wave(IntEnum):
    """2 parameters use this list: OSC1 WAVE, OSC2 WAVE

    On Overlord Synth.
    """

    SINE = 0
    TRIANG = 1
    SAWTOOTH = 2
    SQUARE = 3
    PULSE = 4
    PINK_NS = 5    # 'Pink NS'
    WHITE_NS = 6    # 'White NS'


class OutMode(IntEnum):
    """1 parameter use this list: OUT MODE

    On Chief CE2W (M).
    """

    MONO = 0
    WET_DRY = 1    # 'Wet/Dry'


class OverlordSynthScale(IntEnum):
    """1 parameter use this list: SCALE

    On Overlord Synth.
    """

    MAJOR = 0
    HARMONIC_MINOR = 1    # 'Harmonic Minor'
    MELODIC_MINOR = 2    # 'Melodic Minor'
    NATURAL_MINOR = 3    # 'Natural Minor'


class Peak(IntEnum):
    """1 parameter use this list: PEAK

    On Obsessive Drive.
    """

    LP = 0
    HP = 1


class PetrucciChorus1Mode(IntEnum):
    """1 parameter use this list: MODE

    On Petrucci Chorus 1.
    """

    TRI = 0
    NORM = 1


class PetrucciPhaserMode(IntEnum):
    """1 parameter use this list: MODE

    On Petrucci Phaser.
    """

    PHASE = 0
    VIBE = 1


class PhaseLockedLoopMultiplier(IntEnum):
    """1 parameter use this list: MULTIPLIER

    On Phase-Locked Loop.
    """

    X1 = 0
    X2 = 1
    X3 = 2
    X4 = 3
    X5 = 4
    X6 = 5
    X7 = 6
    X8 = 7


class Pickup(IntEnum):
    """1 parameter use this list: PICKUP

    On Facial Fuzz.
    """

    HB = 0
    SINGLE = 1


class PitchPattern(IntEnum):
    """1 parameter use this list: PITCH PATTERN

    On Glitch.
    """

    DOWN = 0
    UP = 1
    UP_DOWN = 2    # 'Up Down'


class PliniChorusMode(IntEnum):
    """2 parameters use this list: MODE

    On Petrucci Chorus 2, Plini Chorus.
    """

    SPATIAL = 0
    VINTAGE = 1


class PliniDriveMode(IntEnum):
    """1 parameter use this list: MODE

    On Plini Drive.
    """

    FZ = 0
    OD = 1


class PreRoll(IntEnum):
    """1 parameter use this list: PRE ROLL

    On Looper X.
    """

    OFF = 0
    N1_BAR = 1    # '1 BAR'
    N2_BARS = 2    # '2 BARS'
    N4_BARS = 3    # '4 BARS'


class Preset(IntEnum):
    """1 parameter use this list: PRESET

    On Misha Laser.
    """

    PITCH_DISSONANT_WHAM = 0    # 'PITCH - Dissonant Wham'
    PITCH_DUAL_WHAM = 1    # 'PITCH - Dual Wham'
    PITCH_INV_5TH_CHORD = 2    # 'PITCH - Inv 5th Chord'
    PITCH_INVERTED_ATONAL = 3    # 'PITCH - Inverted Atonal'
    PITCH_INVERTED_WHAM = 4    # 'PITCH - Inverted Wham'
    PITCH_INVERTED_WHAM2 = 5    # 'PITCH - Inverted Wham2'
    PITCH_LEAD_FX = 6    # 'PITCH - Lead FX'
    PITCH_LEAD_FX2 = 7    # 'PITCH - Lead FX2'
    PITCH_LOW_TO_HIGH_5TH = 8    # 'PITCH - Low to High 5th'
    PITCH_OCT_5TH_UP = 9    # 'PITCH - Oct + 5th up'
    PITCH_OFF_KEY_DROP1 = 10    # 'PITCH - Off-Key Drop1'
    PITCH_OFF_KEY_DROP2 = 11    # 'PITCH - Off-Key Drop2'
    PITCH_SUPER_WHAM = 12    # 'PITCH - Super Wham'
    RING_CRAZY = 13    # 'RING - Crazy'
    RING_EXTREME_LASERS = 14    # 'RING - Extreme Lasers'
    RING_FAUX_VIBE = 15    # 'RING - Faux Vibe'
    RING_PITCH_TRACKED = 16    # 'RING - Pitch Tracked'
    RING_PURE_RINGMOD = 17    # 'RING - Pure RingMod'
    RING_SANITY = 18    # 'RING - Sanity'


class PunchMode(IntEnum):
    """3 parameters use this list: OVERDUB MODE, PUNCH MODE, RECORD MODE

    On Looper X.
    """

    MOMENTARY = 0
    TOGGLE = 1


class Quality(IntEnum):
    """4 parameters use this list: QUALITY

    On 4 models, among them Analog Delay (M), Analog Delay (ST), Slapback Delay (M).
    """

    N0 = 0    # '0'
    N1 = 1    # '1'
    N2 = 2    # '2'
    N3 = 3    # '3'


class Quantize(IntEnum):
    """1 parameter use this list: QUANTIZE

    On Looper X.
    """

    OFF = 0
    N1_BEAT = 1    # '1 Beat'
    N2_BEATS = 2    # '2 Beats'
    N3_BEATS = 3    # '3 Beats'
    N4_BEATS = 4    # '4 Beats'
    N5_BEATS = 5    # '5 Beats'
    N6_BEATS = 6    # '6 Beats'
    N7_BEATS = 7    # '7 Beats'
    N8_BEATS = 8    # '8 Beats'
    N16_BEATS = 9    # '16 Beats'


class RabeaColossusFuzzMode(IntEnum):
    """3 parameters use this list: MODE

    On Rabea Chaos Bed Octaver, Rabea Colossus Fuzz, Rabea Paragon Overdrive.
    """

    MODERN = 0
    VINTAGE = 1


class Range(IntEnum):
    """1 parameter use this list: RANGE

    On John Mayer Antelope Filter.
    """

    LO = 0
    HI = 1


class Ratio3(IntEnum):
    """7 parameters use this list: RATIO

    On 7 models, among them Nolly Compressor, Plini Comp, SLO-100® Compressor.
    """

    N2 = 0    # '2'
    N4 = 1    # '4'
    N10 = 2    # '10'


class Ratio5(IntEnum):
    """4 parameters use this list: RATIO

    On 4 models, among them Douglas Shining Comp (M), Legendary 87 (M), Legendary 87 (S/C).
    """

    N4 = 0    # '4'
    N8 = 1    # '8'
    N12 = 2    # '12'
    N20 = 3    # '20'
    ALL = 4


class ReadPoint(IntEnum):
    """1 parameter use this list: READ POINT

    On Glitch.
    """

    N0 = 0    # '0'
    N1_64T = 1    # '1/64T'
    N1_64 = 2    # '1/64'
    N1_32T = 3    # '1/32T'
    N1_64D = 4    # '1/64D'
    N1_32 = 5    # '1/32'
    N1_16T = 6    # '1/16T'
    N1_32D = 7    # '1/32D'
    N1_16 = 8    # '1/16'
    N1_8T = 9    # '1/8T'
    N1_16D = 10    # '1/16D'
    N1_8 = 11    # '1/8'
    N1_4T = 12    # '1/4T'
    N1_8D = 13    # '1/8D'
    N1_4 = 14    # '1/4'
    N1_2T = 15    # '1/2T'
    N1_4D = 16    # '1/4D'
    N1_2 = 17    # '1/2'


class RecLength(IntEnum):
    """1 parameter use this list: REC. LENGTH

    On Looper X.
    """

    OFF = 0
    N1_BAR = 1    # '1 BAR'
    N2_BARS = 2    # '2 BARS'
    N3_BARS = 3    # '3 BARS'
    N4_BARS = 4    # '4 BARS'
    N5_BARS = 5    # '5 BARS'
    N6_BARS = 6    # '6 BARS'
    N7_BARS = 7    # '7 BARS'
    N8_BARS = 8    # '8 BARS'
    N9_BARS = 9    # '9 BARS'
    N10_BARS = 10    # '10 BARS'
    N11_BARS = 11    # '11 BARS'
    N12_BARS = 12    # '12 BARS'
    N13_BARS = 13    # '13 BARS'
    N14_BARS = 14    # '14 BARS'
    N15_BARS = 15    # '15 BARS'
    N16_BARS = 16    # '16 BARS'
    N17_BARS = 17    # '17 BARS'
    N18_BARS = 18    # '18 BARS'
    N19_BARS = 19    # '19 BARS'
    N20_BARS = 20    # '20 BARS'
    N21_BARS = 21    # '21 BARS'
    N22_BARS = 22    # '22 BARS'
    N23_BARS = 23    # '23 BARS'
    N24_BARS = 24    # '24 BARS'
    N25_BARS = 25    # '25 BARS'
    N26_BARS = 26    # '26 BARS'
    N27_BARS = 27    # '27 BARS'
    N28_BARS = 28    # '28 BARS'
    N29_BARS = 29    # '29 BARS'
    N30_BARS = 30    # '30 BARS'
    N31_BARS = 31    # '31 BARS'
    N32_BARS = 32    # '32 BARS'


class RedDriveMode(IntEnum):
    """2 parameters use this list: INPUT, MODE

    On Fortin® Nameless, Red Drive.
    """

    LOW = 0
    HIGH = 1


class Resonance(IntEnum):
    """1 parameter use this list: RESONANCE

    On Flanger Engine.
    """

    FULL = 0
    HOLLOW = 1
    RICH = 2
    INTENSE = 3


class Response(IntEnum):
    """1 parameter use this list: RESPONSE

    On John Mayer Antelope Filter.
    """

    SLOW = 0
    FAST = 1


class RingModulatorMultiplier(IntEnum):
    """1 parameter use this list: MULTIPLIER

    On Ring Modulator.
    """

    N4 = 0    # '/4'
    N3 = 1    # '/3'
    N2 = 2    # '/2'
    X1 = 3
    X2 = 4
    X3 = 5
    X4 = 6


class RoomLDist(IntEnum):
    """2 parameters use this list: ROOM L DIST., ROOM R DIST.

    On Petrucci Default Cabsim.
    """

    CLOSE = 0
    MID = 1
    FAR = 2


class RoomSize(IntEnum):
    """1 parameter use this list: ROOM SIZE

    On John Mayer Three-In-One.
    """

    SMALL = 0
    MEDIUM = 1
    LARGE = 2


class Root(IntEnum):
    """1 parameter use this list: ROOT

    On Overlord Synth.
    """

    OFF = 0
    A = 1
    A_2 = 2    # 'A#'
    B = 3
    C = 4
    C_5 = 5    # 'C#'
    D = 6
    D_7 = 7    # 'D#'
    E = 8
    F = 9
    F_10 = 10    # 'F#'
    G = 11
    G_12 = 12    # 'G#'


class RotaryAttack(IntEnum):
    """3 parameters use this list: ATTACK, SPEED

    On Rotary, SLO-100® Compressor, Tim Henson Compressor.
    """

    SLOW = 0
    FAST = 1


class Routing(IntEnum):
    """1 parameter use this list: ROUTING

    On TempoControl.
    """

    MULTI = 0
    HP = 1
    OUT_1_2 = 2    # 'OUT 1/2'
    OUT_3_4 = 3    # 'OUT 3/4'
    SEND_1_2 = 4    # 'SEND 1/2'


class RoutingMode(IntEnum):
    """1 parameter use this list: ROUTING MODE

    On Looper X.
    """

    GRID = 0
    IN_1 = 1    # 'In 1'
    IN_2 = 2    # 'In 2'
    RET_1 = 3    # 'Ret 1'
    RET_2 = 4    # 'Ret 2'
    IN_1_2 = 5    # 'In 1/2'
    RET_1_2 = 6    # 'Ret 1/2'
    OUT1 = 7
    OUT2 = 8
    OUT3 = 9
    OUT4 = 10
    OUT1_2 = 11    # 'Out1/2'
    OUT3_4 = 12    # 'Out3/4'
    MULTI = 13


class Size(IntEnum):
    """18 parameters use this list: ROOM SIZE, SIZE

    On 18 models, among them Ambience, Dual (M), Dual (M) Lite.
    """

    SMALL = 0
    MED = 1
    LARGE = 2


class SlapbackDelayMSyncNote(IntEnum):
    """2 parameters use this list: SYNC NOTE

    On Slapback Delay (M), Slapback Delay (ST).
    """

    N1_64T = 0    # '1/64T'
    N1_64 = 1    # '1/64'
    N1_32T = 2    # '1/32T'
    N1_64D = 3    # '1/64D'
    N1_32 = 4    # '1/32'
    N1_16T = 5    # '1/16T'
    N1_32D = 6    # '1/32D'
    N1_16 = 7    # '1/16'
    N1_8T = 8    # '1/8T'
    N1_16D = 9    # '1/16D'
    N1_8 = 10    # '1/8'


class Slope(IntEnum):
    """1 parameter use this list: SLOPE

    On Overlord Synth.
    """

    N6DB_OCT = 0    # '6dB/Oct'
    N12DB_OCT = 1    # '12dB/Oct'
    N18DB_OCT = 2    # '18dB/Oct'
    N24DB_OCT = 3    # '24dB/Oct'


class SoldanoSlo100Channel(IntEnum):
    """1 parameter use this list: CHANNEL

    On Soldano SLO-100®.
    """

    CLEAN = 0
    CRUNCH = 1
    LEAD = 2


class Sound(IntEnum):
    """1 parameter use this list: SOUND

    On TempoControl.
    """

    BLIP = 0
    BLOCK = 1
    COWBELL = 2
    DIGITAL = 3
    DRUM_KIT = 4    # 'DRUM KIT'
    SOFT_KIT = 5    # 'SOFT KIT'


class SplitterMode(IntEnum):
    """2 parameters use this list: MODE

    On Splitter, Splitter Crossover.
    """

    REGULAR = 0
    INVERT = 1


class SplitterType(IntEnum):
    """1 parameter use this list: TYPE

    On Splitter.
    """

    BALANCE = 0
    A_B = 1    # 'A/B'
    CROSSOVER = 2


class Start(IntEnum):
    """2 parameters use this list: METRONOME MUTE, START

    On Looper X, TempoControl.
    """

    MUTE = 0
    UNMUTE = 1


class Stereo(IntEnum):
    """4 parameters use this list: STEREO

    On 4 models, among them Splitter, Splitter AB, Splitter Balance.
    """

    NORMAL = 0
    SPLIT = 1


class StereoLink(IntEnum):
    """1 parameter use this list: STEREO LINK

    On Phase Doctor.
    """

    UNLINKED = 0
    LINKED = 1


class Sweep(IntEnum):
    """1 parameter use this list: SWEEP

    On John Mayer Antelope Filter.
    """

    DOWN = 0
    UP = 1


class SyncNote11(IntEnum):
    """6 parameters use this list: CHR NOTE, SYNC NOTE

    On 6 models, among them Chief DC2W PCOM, Chorus 229T, Cory Wong The 80s.
    """

    N1_8 = 0    # '1/8'
    N1_4T = 1    # '1/4T'
    N1_8D = 2    # '1/8D'
    N1_4 = 3    # '1/4'
    N1_2T = 4    # '1/2T'
    N1_4D = 5    # '1/4D'
    N1_2 = 6    # '1/2'
    N1_1T = 7    # '1/1T'
    N1_2D = 8    # '1/2D'
    N1_1 = 9    # '1/1'
    N1_1D = 10    # '1/1D'


class SyncNote14(IntEnum):
    """10 parameters use this list: SYNC NOTE

    On 10 models, among them Chief CE2W (M), Chief CE2W (ST), Dream Chorus (M).
    """

    N1_16 = 0    # '1/16'
    N1_8T = 1    # '1/8T'
    N1_16D = 2    # '1/16D'
    N1_8 = 3    # '1/8'
    N1_4T = 4    # '1/4T'
    N1_8D = 5    # '1/8D'
    N1_4 = 6    # '1/4'
    N1_2T = 7    # '1/2T'
    N1_4D = 8    # '1/4D'
    N1_2 = 9    # '1/2'
    N1_1T = 10    # '1/1T'
    N1_2D = 11    # '1/2D'
    N1_1 = 12    # '1/1'
    N1_1D = 13    # '1/1D'


class SyncNote17(IntEnum):
    """16 parameters use this list: FAST NOTE, SLOW NOTE, SYNC NOTE

    On 14 models, among them Chorus Engine, Digital Flanger, Flanger Engine.
    """

    N1_32 = 0    # '1/32'
    N1_16T = 1    # '1/16T'
    N1_32D = 2    # '1/32D'
    N1_16 = 3    # '1/16'
    N1_8T = 4    # '1/8T'
    N1_16D = 5    # '1/16D'
    N1_8 = 6    # '1/8'
    N1_4T = 7    # '1/4T'
    N1_8D = 8    # '1/8D'
    N1_4 = 9    # '1/4'
    N1_2T = 10    # '1/2T'
    N1_4D = 11    # '1/4D'
    N1_2 = 12    # '1/2'
    N1_1T = 13    # '1/1T'
    N1_2D = 14    # '1/2D'
    N1_1 = 15    # '1/1'
    N1_1D = 16    # '1/1D'


class SyncNote21(IntEnum):
    """44 parameters use this list: FEEDBACK SYNC NOTE, SYNC NOTE, SYNC NOTE A, SYNC NOTE B, SYNC NOTE L, SYNC NOTE R, ...

    On 34 models, among them Arpeggio Delay, Circular Delay, Cory Wong Delay-y-y.
    """

    N1_64T = 0    # '1/64T'
    N1_64 = 1    # '1/64'
    N1_32T = 2    # '1/32T'
    N1_64D = 3    # '1/64D'
    N1_32 = 4    # '1/32'
    N1_16T = 5    # '1/16T'
    N1_32D = 6    # '1/32D'
    N1_16 = 7    # '1/16'
    N1_8T = 8    # '1/8T'
    N1_16D = 9    # '1/16D'
    N1_8 = 10    # '1/8'
    N1_4T = 11    # '1/4T'
    N1_8D = 12    # '1/8D'
    N1_4 = 13    # '1/4'
    N1_2T = 14    # '1/2T'
    N1_4D = 15    # '1/4D'
    N1_2 = 16    # '1/2'
    N1_1T = 17    # '1/1T'
    N1_2D = 18    # '1/2D'
    N1_1 = 19    # '1/1'
    N1_1D = 20    # '1/1D'


class SyncOn(IntEnum):
    """1 parameter use this list: SYNC ON

    On Harmonic Tremolo.
    """

    LOWS = 0
    HIGHS = 1


class SyncSource(IntEnum):
    """1 parameter use this list: SYNC SOURCE

    On Glitch.
    """

    GLOBAL_ = 0    # 'Global'
    BLOCK = 1


class TankType(IntEnum):
    """2 parameters use this list: TANK TYPE

    On Spring Reverb Engine (M), Spring Reverb Engine (ST).
    """

    VINTAGE = 0
    SHORT = 1
    MID = 2
    LONG = 3


class Tap1Interval(IntEnum):
    """3 parameters use this list: TAP 1 INTERVAL, TAP 2 INTERVAL, TAP 3 INTERVAL

    On Arpeggio Delay.
    """

    MINUS_13TH = 0    # '-13th'
    MINUS_12TH = 1    # '-12th'
    MINUS_11TH = 2    # '-11th'
    MINUS_10TH = 3    # '-10th'
    MINUS_9TH = 4    # '-9th'
    MINUS_8VE = 5    # '-8ve'
    MINUS_7TH = 6    # '-7th'
    MINUS_6TH = 7    # '-6th'
    MINUS_5TH = 8    # '-5th'
    MINUS_4TH = 9    # '-4th'
    MINUS_3RD = 10    # '-3rd'
    MINUS_2ND = 11    # '-2nd'
    ROOT = 12
    N2ND = 13    # '2nd'
    N3RD = 14    # '3rd'
    N4TH = 15    # '4th'
    N5TH = 16    # '5th'
    N6TH = 17    # '6th'
    N7TH = 18    # '7th'
    N8VE = 19    # '8ve'
    N9TH = 20    # '9th'
    N10TH = 21    # '10th'
    N11TH = 22    # '11th'
    N12TH = 23    # '12th'
    N13TH = 24    # '13th'


class Tap1Semitones(IntEnum):
    """3 parameters use this list: TAP 1 SEMITONES, TAP 2 SEMITONES, TAP 3 SEMITONES

    On Arpeggio Delay.
    """

    MINUS_12 = 0    # '-12'
    MINUS_11 = 1    # '-11'
    MINUS_10 = 2    # '-10'
    MINUS_9 = 3    # '-9'
    MINUS_8 = 4    # '-8'
    MINUS_7 = 5    # '-7'
    MINUS_6 = 6    # '-6'
    MINUS_5 = 7    # '-5'
    MINUS_4 = 8    # '-4'
    MINUS_3 = 9    # '-3'
    MINUS_2 = 10    # '-2'
    MINUS_1 = 11    # '-1'
    N0 = 12    # '0'
    N1 = 13    # '1'
    N2 = 14    # '2'
    N3 = 15    # '3'
    N4 = 16    # '4'
    N5 = 17    # '5'
    N6 = 18    # '6'
    N7 = 19    # '7'
    N8 = 20    # '8'
    N9 = 21    # '9'
    N10 = 22    # '10'
    N11 = 23    # '11'
    N12 = 24    # '12'


class TapPreset(IntEnum):
    """1 parameter use this list: TAP PRESET

    On Circular Delay.
    """

    N1 = 0    # '1'
    N2 = 1    # '2'
    N3 = 2    # '3'
    N4 = 3    # '4'
    N4_ALT = 4    # '4 Alt'
    N5 = 5    # '5'
    N5_ALT = 6    # '5 Alt'
    N6 = 7    # '6'
    N6_ALT = 8    # '6 Alt'


class TempoSource(IntEnum):
    """1 parameter use this list: TEMPO SOURCE

    On John Mayer Dream Delay (ST).
    """

    GLOBAL_ = 0    # 'Global'
    LOCAL = 1


class TempocontrolType(IntEnum):
    """1 parameter use this list: TYPE

    On TempoControl.
    """

    PRESET = 0
    GLOBAL_ = 1    # 'Global'


class TimHensonDelayModernMode(IntEnum):
    """3 parameters use this list: MODE

    On Tim Henson Delay Diffusion, Tim Henson Delay Modern, Tim Henson Delay V. Digital.
    """

    NORMAL = 0
    WIDE = 1
    PING_PONG = 2    # 'PING PONG'


class TimeSignature(IntEnum):
    """1 parameter use this list: TIME SIGNATURE

    On TempoControl.
    """

    N2_4 = 0    # '2/4'
    N3_4 = 1    # '3/4'
    N4_4 = 2    # '4/4'
    N5_4 = 3    # '5/4'
    N6_4 = 4    # '6/4'
    N7_4 = 5    # '7/4'
    N8_4 = 6    # '8/4'
    N9_4 = 7    # '9/4'
    N10_4 = 8    # '10/4'
    N11_4 = 9    # '11/4'
    N12_4 = 10    # '12/4'
    N13_4 = 11    # '13/4'
    N3_8 = 12    # '3/8'
    N6_8 = 13    # '6/8'
    N9_8 = 14    # '9/8'
    N12_8 = 15    # '12/8'
    N5_8_3_2 = 16    # '5/8 (3+2)'
    N5_8_2_3 = 17    # '5/8 (2+3)'
    N7_8_3_2_2 = 18    # '7/8 (3+2+2)'
    N7_8_2_3_2 = 19    # '7/8 (2+3+2)'
    N7_8_2_2_3 = 20    # '7/8 (2+2+3)'


class TremoloWaveform(IntEnum):
    """2 parameters use this list: WAVEFORM

    On Harmonic Tremolo, Tremolo.
    """

    SINE = 0
    TRIANGLE = 1
    SQUARE = 2
    SAW_UP = 3    # 'Saw Up'
    SAW_DN = 4    # 'Saw Dn'


class TrigDirection(IntEnum):
    """1 parameter use this list: TRIG DIRECTION

    On Love Meat.
    """

    DOWN = 0
    UP = 1


class Trigger(IntEnum):
    """1 parameter use this list: TRIGGER

    On Misha Laser.
    """

    RELEASE = 0
    TRIGGER = 1


class TriggerMode(IntEnum):
    """1 parameter use this list: TRIGGER MODE

    On Love Meat.
    """

    OFF = 0
    FULL = 1
    N1_2 = 2    # '1/2'


class Tube(IntEnum):
    """4 parameters use this list: TUBE

    On 4 models, among them Rabea Crunch, Rabea Lead, Victor Squid Ch1.
    """

    N6L6 = 0    # '6L6'
    EL34 = 1


class UnisonSource(IntEnum):
    """1 parameter use this list: UNISON SOURCE

    On Overlord Synth.
    """

    OFF = 0
    OSC_1 = 1    # 'OSC 1'
    OSC_2 = 2    # 'OSC 2'
    OSC_1_2 = 3    # 'OSC 1 + 2'


class UsDlx64VintageMode(IntEnum):
    """2 parameters use this list: MODE

    On US DLX 64 Vintage, US DLX 65 Reissue.
    """

    NORMAL = 0
    VIBRATO = 1
    VIBRATO_BRIGHT_OFF = 2    # 'Vibrato Bright Off'


class V1Active(IntEnum):
    """4 parameters use this list: V1 ACTIVE, V2 ACTIVE, V3 ACTIVE, V4 ACTIVE

    On Multivoicer.
    """

    NO = 0
    YES = 1


class VibNote(IntEnum):
    """2 parameters use this list: VIB NOTE

    On Cory Wong The 80s, Vintage Chorus.
    """

    N1_32 = 0    # '1/32'
    N1_16T = 1    # '1/16T'
    N1_32D = 2    # '1/32D'
    N1_16 = 3    # '1/16'
    N1_8T = 4    # '1/8T'
    N1_16D = 5    # '1/16D'
    N1_8 = 6    # '1/8'
    N1_4T = 7    # '1/4T'
    N1_8D = 8    # '1/8D'


class VintageChorusMode(IntEnum):
    """2 parameters use this list: MODE

    On Cory Wong The 80s, Vintage Chorus.
    """

    CHORUS = 0
    VIBRATO = 1


class Voice(IntEnum):
    """1 parameter use this list: VOICE

    On Misha Clean.
    """

    NORMAL = 0
    THICKER = 1


class VoiceMode(IntEnum):
    """1 parameter use this list: VOICE MODE

    On Chorus Engine.
    """

    FULL = 0
    THICK = 1
    OPEN = 2
    BROAD = 3


class VoiceView(IntEnum):
    """1 parameter use this list: VOICE VIEW

    On Multivoicer.
    """

    DETUNE_DLY = 0    # 'Detune/Dly'
    LEVEL_PAN = 1    # 'Level/Pan'


class Voicing(IntEnum):
    """1 parameter use this list: VOICING

    On Multivoicer.
    """

    TRIADS_CLOSED_TRIAD_3_R_5 = 0    # 'Triads¤Closed Triad (3-R-5)'
    TRIADS_CLOSED_TRIAD_1_3_R_5_1 = 1    # 'Triads¤Closed Triad (1-3-R-5-1)'
    TRIADS_OPEN_TRIAD_5_R_3 = 2    # 'Triads¤Open Triad (5-R-3)'
    TRIADS_OPEN_TRIAD_5_5_R_3_5 = 3    # 'Triads¤Open Triad (5-5-R-3-5)'
    SEVENTH_CHORDS_CLOSED_7TH_CHORD_3_R_7 = 4    # 'Seventh Chords¤Closed 7th Chord (3-R-7)'
    SEVENTH_CHORDS_CLOSED_7TH_CHORD_7_3_R_5_7 = 5    # 'Seventh Chords¤Closed 7th Chord (7-3-R-5-7)'
    SEVENTH_CHORDS_OPEN_7TH_CHORD_3_5_R_7_3 = 6    # 'Seventh Chords¤Open 7th Chord (3-5-R-7-3)'
    DROPS_LOWER_ROOT_TRIAD_1_3_R_5_1 = 7    # 'Drops¤Lower Root Triad (1-3-R-5-1)'
    DROPS_LOWER_ROOT_7TH_CHORD_1_3_R_7_1 = 8    # 'Drops¤Lower Root 7th Chord (1-3-R-7-1)'
    DROPS_DROP_2_5_3_R_7_5 = 9    # 'Drops¤Drop 2 (5-3-R-7-5)'
    DROPS_DROP_3_3_5_R_7_3 = 10    # 'Drops¤Drop 3 (3-5-R-7-3)'
    DROPS_DROP_2_4_1_5_R_3_7 = 11    # 'Drops¤Drop 2-4 (1-5-R-3-7)'
    TENSIONS_9TH_7_3_R_5_2 = 12    # 'Tensions¤9th (7-3-R-5-2)'
    TENSIONS_11TH_7_3_R_2_4 = 13    # 'Tensions¤11th (7-3-R-2-4)'
    TENSIONS_13TH_7_2_R_4_6 = 14    # 'Tensions¤13th (7-2-R-4-6)'
    TONE_CLUSTERS_SECUNDALS_1_2_3_R_4_5 = 15    # 'Tone Clusters¤Secundals #1 (2-3-R-4-5)'
    TONE_CLUSTERS_SECUNDALS_2_7_4_R_5_6 = 16    # 'Tone Clusters¤Secundals #2 (7-4-R-5-6)'
    OTHER_SUS4_1_5_8_R_4_5 = 17    # 'Other¤Sus4 #1 (5-8-R-4-5)'
    OTHER_SUS9_2_5_8_R_2_5 = 18    # 'Other¤Sus9 #2 (5-8-R-2-5)'
    OTHER_POWER_CHORD_1_5_R_5 = 19    # 'Other¤Power Chord #1 (5-R-5)'
    OTHER_POWER_CHORD_2_8_5_R_5_8 = 20    # 'Other¤Power Chord #2 (8-5-R-5-8)'
    OTHER_FOURTHS_1_4_R_4 = 21    # 'Other¤Fourths #1 (4-R-4)'
    OTHER_FOURTHS_2_8_4_R_4_8 = 22    # 'Other¤Fourths #2 (8-4-R-4-8)'
    OTHER_OCTAVES_UP_1_8_R_8 = 23    # 'Other¤Octaves Up #1 (8-R-8)'
    OTHER_OCTAVES_UP_2_8_8_R_8_8 = 24    # 'Other¤Octaves Up #2 (8-8-R-8-8)'
    OTHER_BIG_UNISON_8_8_R_8_8 = 25    # 'Other¤Big Unison (8-8-R-8-8)'
    OFF = 26


#: Each enum's options as the DEVICE spells them, in wire order.
#:
#: The member names above are ours - mangled to be valid Python, and
#: corrected where the device has a typo. These are the strings the
#: unit actually uses, which is what a dynamic list matches against.
OPTION_LABELS = {
    Adjust: ('Bypass', '90°', '180°'),
    AnalogDelayMSyncNote: ('1/16', '1/8T', '1/16D', '1/8', '1/4T', '1/8D', '1/4', '1/2T', '1/4D', '1/2', '1/1T', '1/2D', '1/1'),
    ArpPattern: ('Up', 'Down', 'Up & Down', 'Down & Up', 'Random'),
    AutoSpeed: ('1/1', '1/2', '1/4', '1/8', '1/16', '1/32'),
    BitDepth: ('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16'),
    Boost: ('HOT', 'COOL'),
    Bright: ('Normal', 'Bright 1', 'Bright 2'),
    Center: ('Lo Freq', 'Hi Freq'),
    ChannelNormal: ('Normal', 'OD'),
    ChiefCe2wMType: ('CE2-C', 'CE1-C', 'CE1-V'),
    ChiefDc2wMMode: ('1', '2', '3', '4', '1+2', '1+3', '1+4', '2+3', '2+4', '3+4'),
    ChiefDc2wMType: ('S', 'SDD-320'),
    Color: ('Natural', 'Warm', 'Dark', 'Bright', 'Sparkle', 'Dusty', 'Spiky', 'Twangy'),
    CoryWongDIFunkConsoleAttack: ('Fast', 'Slow'),
    Crunch: ('Clean', 'Crunch'),
    Curve: ('Linear', 'Log'),
    DCellHisbertCh2Mode: ('-', '+'),
    Decay: ('Fast', 'Smooth'),
    DigitalFlangerPolarity: ('Neg', 'Pos'),
    DivSource: ('Unison', 'Multiplier'),
    Divider: ('2', '3', '4', '5', '6', '7', '8'),
    DoublerInput: ('Left', 'Mono', 'Right'),
    DreamChorusMMode: ('CHO1', 'CHO2'),
    DriveType: ('Soft', 'Edgy', 'Hard', 'Off'),
    DualChorusMode: ('Chorus', 'Vibe'),
    DumbbellOdsChannel: ('Clean', 'OD'),
    DumbbellOdsEq: ('Jazz', 'Rock'),
    DuplicateMode: ('Free', 'Sync'),
    DynMode2: ('Duck', 'Gate'),
    DynMode3: ('Off', 'Duck', 'Gate'),
    Eq3: ('Normal', 'Thick', 'Thicker'),
    FeedbackMode: ('Reverse', 'Flip'),
    Filter: ('4-POLE', '2-POLE'),
    FilterCutoff: ('Low', 'A', 'B', 'High'),
    FilterType: ('Lowpass', 'Bandpass', 'Highpass'),
    FlangerEngineWaveform: ('Sine', 'Triangle', 'Square', 'Saw Up', 'Saw Dn', 'rndSmooth', 'rndStep'),
    Focus: ('ON', 'OFF'),
    Freeze: ('RELEASE', 'FREEZE'),
    Frequency: ('1', '2', '3', '4', '5'),
    GOccurrence: ('1/4', '1/8', '1/16', '1/32'),
    GainPolarity: ('Normal', 'Inverted'),
    GlitchMode: ('Sequence', 'Pitch Delay', 'Interfere', 'Texturizer'),
    GojiraWowMode: ('Blade 2', 'Blade 1', 'FATSO'),
    GrainLength: ('1/64', '1/32', '1/16', '1/8', '1/4', '1/2', '1/1'),
    HighsFreq: ('4 kHz', '2.5 kHz'),
    HorizonDevicesPrecisionDriveAttack: ('470', '330', '100', '68', '47', '33'),
    HpfSlope: ('Flat', '-6', '-12', '-18', '-24', '-30', '-36', '-42', '-48'),
    Instrument: ('Guitar', 'Bass'),
    Invert: ('Noral', 'Inverted'),
    JohnMayerHeadroomHeroInput: ('NORMAL', 'FET'),
    JohnMayerSignature83Eq: ('EQ1', 'EQ2'),
    Key: ('A', 'A#', 'B', 'C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#'),
    LoopLength: ('1/2 BAR', '1 BAR', '2 BARS', '4 BARS'),
    LowsFreq: ('225 Hz', '150 Hz'),
    M: ('Ring', 'Pitch'),
    Mid: ('Off', 'Boost'),
    MidsFreq: ('900 Hz', '600 Hz'),
    MinivoicerMidiCh: ('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', 'Omni'),
    MinivoicerMode: ('Major', 'Harmonic Minor', 'Natural Minor', 'Melodic Minor', 'Chromatic'),
    MinivoicerV1Interval: ('-15th', '-14th', '-13th', '-12th', '-11th', '-10th', '-9th', '-8th', '-7th', '-6th', '-5th', '-4th', '-3rd', '-2nd', 'Root', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th', '11th', '12th', '13th', '14th', '15th'),
    MishaLaserMode: ('Pedal', 'Envelope'),
    MishaModulatorMode: ('Chorus', 'Flanger'),
    MishaRhythmInput: ('Low', 'High'),
    MishaStereoDelayMode: ('Stereo', 'Phase Inv', 'Ping Pong'),
    MixLaw: ('nolly', 'nollySkewed', 'nollySkewedPlug'),
    ModSource: ('LFO', 'LFO Stereo', '+Envelope', '-Envelope'),
    Mode2: ('Single', 'Dual'),
    Model: ('TS', 'BB'),
    MulSource: ('Unison', '-1 Octave', '-2 Octaves'),
    MultivoicerMidiCh: ('Off', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', 'Omni'),
    MultivoicerScale: ('Chromatic', 'Major', 'Natural Minor', 'Harmonic Minor', 'Melodic Minor'),
    MultivoicerV1Interval: ('-15th', '-14th', '-13th', '-12th', '-11th', '-10th', '-9th', '-8th', '-7th', '-6th', '-5th', '-4th', '-3rd', '-2nd', 'Root', '+2nd', '+3rd', '+4th', '+5th', '+6th', '+7th', '+8th', '+9th', '+10th', '+11th', '+12th', '+13th', '+14th', '+15th'),
    MxPhase95Mode: ('Block', 'Script'),
    MxPhase95Type: ('90', '45'),
    NollyCompressorAttack: ('Smooth', 'Snappy'),
    Notelength: ('QUARTER', 'EIGHTH', 'TRIPLET', 'SIXTEENTH'),
    Octave: ('-2', '-1', '0', '1', '2'),
    Osc1Wave: ('Sine', 'Triang', 'Sawtooth', 'Square', 'Pulse', 'Pink NS', 'White NS'),
    OutMode: ('Mono', 'Wet/Dry'),
    OverlordSynthScale: ('Major', 'Harmonic Minor', 'Melodic Minor', 'Natural Minor'),
    Peak: ('LP', 'HP'),
    PetrucciChorus1Mode: ('Tri', 'Norm'),
    PetrucciPhaserMode: ('Phase', 'Vibe'),
    PhaseLockedLoopMultiplier: ('x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8'),
    Pickup: ('HB', 'SINGLE'),
    PitchPattern: ('Down', 'Up', 'Up Down'),
    PliniChorusMode: ('Spatial', 'Vintage'),
    PliniDriveMode: ('FZ', 'OD'),
    PreRoll: ('OFF', '1 BAR', '2 BARS', '4 BARS'),
    Preset: ('PITCH - Dissonant Wham', 'PITCH - Dual Wham', 'PITCH - Inv 5th Chord', 'PITCH - Inverted Atonal', 'PITCH - Inverted Wham', 'PITCH - Inverted Wham2', 'PITCH - Lead FX', 'PITCH - Lead FX2', 'PITCH - Low to High 5th', 'PITCH - Oct + 5th up', 'PITCH - Off-Key Drop1', 'PITCH - Off-Key Drop2', 'PITCH - Super Wham', 'RING - Crazy', 'RING - Extreme Lasers', 'RING - Faux Vibe', 'RING - Pitch Tracked', 'RING - Pure RingMod', 'RING - Sanity'),
    PunchMode: ('Momentary', 'Toggle'),
    Quality: ('0', '1', '2', '3'),
    Quantize: ('OFF', '1 Beat', '2 Beats', '3 Beats', '4 Beats', '5 Beats', '6 Beats', '7 Beats', '8 Beats', '16 Beats'),
    RabeaColossusFuzzMode: ('Modern', 'Vintage'),
    Range: ('LO', 'HI'),
    Ratio3: ('2', '4', '10'),
    Ratio5: ('4', '8', '12', '20', 'All'),
    ReadPoint: ('0', '1/64T', '1/64', '1/32T', '1/64D', '1/32', '1/16T', '1/32D', '1/16', '1/8T', '1/16D', '1/8', '1/4T', '1/8D', '1/4', '1/2T', '1/4D', '1/2'),
    RecLength: ('OFF', '1 BAR', '2 BARS', '3 BARS', '4 BARS', '5 BARS', '6 BARS', '7 BARS', '8 BARS', '9 BARS', '10 BARS', '11 BARS', '12 BARS', '13 BARS', '14 BARS', '15 BARS', '16 BARS', '17 BARS', '18 BARS', '19 BARS', '20 BARS', '21 BARS', '22 BARS', '23 BARS', '24 BARS', '25 BARS', '26 BARS', '27 BARS', '28 BARS', '29 BARS', '30 BARS', '31 BARS', '32 BARS'),
    RedDriveMode: ('LOW', 'HIGH'),
    Resonance: ('Full', 'Hollow', 'Rich', 'Intense'),
    Response: ('SLOW', 'FAST'),
    RingModulatorMultiplier: ('/4', '/3', '/2', 'x1', 'x2', 'x3', 'x4'),
    RoomLDist: ('Close', 'Mid', 'Far'),
    RoomSize: ('Small', 'Medium', 'Large'),
    Root: ('OFF', 'A', 'A#', 'B', 'C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#'),
    RotaryAttack: ('Slow', 'Fast'),
    Routing: ('MULTI', 'HP', 'OUT 1/2', 'OUT 3/4', 'SEND 1/2'),
    RoutingMode: ('Grid', 'In 1', 'In 2', 'Ret 1', 'Ret 2', 'In 1/2', 'Ret 1/2', 'Out1', 'Out2', 'Out3', 'Out4', 'Out1/2', 'Out3/4', 'Multi'),
    Size: ('Small', 'Med', 'Large'),
    SlapbackDelayMSyncNote: ('1/64T', '1/64', '1/32T', '1/64D', '1/32', '1/16T', '1/32D', '1/16', '1/8T', '1/16D', '1/8'),
    Slope: ('6dB/Oct', '12dB/Oct', '18dB/Oct', '24dB/Oct'),
    SoldanoSlo100Channel: ('Clean', 'Crunch', 'Lead'),
    Sound: ('BLIP', 'BLOCK', 'COWBELL', 'DIGITAL', 'DRUM KIT', 'SOFT KIT'),
    SplitterMode: ('Regular', 'Invert'),
    SplitterType: ('Balance', 'A/B', 'Crossover'),
    Start: ('MUTE', 'UNMUTE'),
    Stereo: ('Normal', 'Split'),
    StereoLink: ('Unlinked', 'Linked'),
    Sweep: ('DOWN', 'UP'),
    SyncNote11: ('1/8', '1/4T', '1/8D', '1/4', '1/2T', '1/4D', '1/2', '1/1T', '1/2D', '1/1', '1/1D'),
    SyncNote14: ('1/16', '1/8T', '1/16D', '1/8', '1/4T', '1/8D', '1/4', '1/2T', '1/4D', '1/2', '1/1T', '1/2D', '1/1', '1/1D'),
    SyncNote17: ('1/32', '1/16T', '1/32D', '1/16', '1/8T', '1/16D', '1/8', '1/4T', '1/8D', '1/4', '1/2T', '1/4D', '1/2', '1/1T', '1/2D', '1/1', '1/1D'),
    SyncNote21: ('1/64T', '1/64', '1/32T', '1/64D', '1/32', '1/16T', '1/32D', '1/16', '1/8T', '1/16D', '1/8', '1/4T', '1/8D', '1/4', '1/2T', '1/4D', '1/2', '1/1T', '1/2D', '1/1', '1/1D'),
    SyncOn: ('Lows', 'Highs'),
    SyncSource: ('Global', 'Block'),
    TankType: ('Vintage', 'Short', 'Mid', 'Long'),
    Tap1Interval: ('-13th', '-12th', '-11th', '-10th', '-9th', '-8ve', '-7th', '-6th', '-5th', '-4th', '-3rd', '-2nd', 'Root', '2nd', '3rd', '4th', '5th', '6th', '7th', '8ve', '9th', '10th', '11th', '12th', '13th'),
    Tap1Semitones: ('-12', '-11', '-10', '-9', '-8', '-7', '-6', '-5', '-4', '-3', '-2', '-1', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'),
    TapPreset: ('1', '2', '3', '4', '4 Alt', '5', '5 Alt', '6', '6 Alt'),
    TempoSource: ('Global', 'Local'),
    TempocontrolType: ('Preset', 'Global'),
    TimHensonDelayModernMode: ('NORMAL', 'WIDE', 'PING PONG'),
    TimeSignature: ('2/4', '3/4', '4/4', '5/4', '6/4', '7/4', '8/4', '9/4', '10/4', '11/4', '12/4', '13/4', '3/8', '6/8', '9/8', '12/8', '5/8 (3+2)', '5/8 (2+3)', '7/8 (3+2+2)', '7/8 (2+3+2)', '7/8 (2+2+3)'),
    TremoloWaveform: ('Sine', 'Triangle', 'Square', 'Saw Up', 'Saw Dn'),
    TrigDirection: ('Down', 'Up'),
    Trigger: ('RELEASE', 'TRIGGER'),
    TriggerMode: ('Off', 'Full', '1/2'),
    Tube: ('6L6', 'EL34'),
    UnisonSource: ('OFF', 'OSC 1', 'OSC 2', 'OSC 1 + 2'),
    UsDlx64VintageMode: ('Normal', 'Vibrato', 'Vibrato Bright Off'),
    V1Active: ('No', 'Yes'),
    VibNote: ('1/32', '1/16T', '1/32D', '1/16', '1/8T', '1/16D', '1/8', '1/4T', '1/8D'),
    VintageChorusMode: ('Chorus', 'Vibrato'),
    Voice: ('Normal', 'Thicker'),
    VoiceMode: ('Full', 'Thick', 'Open', 'Broad'),
    VoiceView: ('Detune/Dly', 'Level/Pan'),
    Voicing: ('Triads¤Closed Triad (3-R-5)', 'Triads¤Closed Triad (1-3-R-5-1)', 'Triads¤Open Triad (5-R-3)', 'Triads¤Open Triad (5-5-R-3-5)', 'Seventh Chords¤Closed 7th Chord (3-R-7)', 'Seventh Chords¤Closed 7th Chord (7-3-R-5-7)', 'Seventh Chords¤Open 7th Chord (3-5-R-7-3)', 'Drops¤Lower Root Triad (1-3-R-5-1)', 'Drops¤Lower Root 7th Chord (1-3-R-7-1)', 'Drops¤Drop 2 (5-3-R-7-5)', 'Drops¤Drop 3 (3-5-R-7-3)', 'Drops¤Drop 2-4 (1-5-R-3-7)', 'Tensions¤9th (7-3-R-5-2)', 'Tensions¤11th (7-3-R-2-4)', 'Tensions¤13th (7-2-R-4-6)', 'Tone Clusters¤Secundals #1 (2-3-R-4-5)', 'Tone Clusters¤Secundals #2 (7-4-R-5-6)', 'Other¤Sus4 #1 (5-8-R-4-5)', 'Other¤Sus9 #2 (5-8-R-2-5)', 'Other¤Power Chord #1 (5-R-5)', 'Other¤Power Chord #2 (8-5-R-5-8)', 'Other¤Fourths #1 (4-R-4)', 'Other¤Fourths #2 (8-4-R-4-8)', 'Other¤Octaves Up #1 (8-R-8)', 'Other¤Octaves Up #2 (8-8-R-8-8)', 'Other¤Big Unison (8-8-R-8-8)', 'Off'),
}


__all__ = [
    "Adjust",
    "AnalogDelayMSyncNote",
    "ArpPattern",
    "AutoSpeed",
    "BitDepth",
    "Boost",
    "Bright",
    "Center",
    "ChannelNormal",
    "ChiefCe2wMType",
    "ChiefDc2wMMode",
    "ChiefDc2wMType",
    "Color",
    "CoryWongDIFunkConsoleAttack",
    "Crunch",
    "Curve",
    "DCellHisbertCh2Mode",
    "Decay",
    "DigitalFlangerPolarity",
    "DivSource",
    "Divider",
    "DoublerInput",
    "DreamChorusMMode",
    "DriveType",
    "DualChorusMode",
    "DumbbellOdsChannel",
    "DumbbellOdsEq",
    "DuplicateMode",
    "DynMode2",
    "DynMode3",
    "Eq3",
    "FeedbackMode",
    "Filter",
    "FilterCutoff",
    "FilterType",
    "FlangerEngineWaveform",
    "Focus",
    "Freeze",
    "Frequency",
    "GOccurrence",
    "GainPolarity",
    "GlitchMode",
    "GojiraWowMode",
    "GrainLength",
    "HighsFreq",
    "HorizonDevicesPrecisionDriveAttack",
    "HpfSlope",
    "Instrument",
    "Invert",
    "JohnMayerHeadroomHeroInput",
    "JohnMayerSignature83Eq",
    "Key",
    "LoopLength",
    "LowsFreq",
    "M",
    "Mid",
    "MidsFreq",
    "MinivoicerMidiCh",
    "MinivoicerMode",
    "MinivoicerV1Interval",
    "MishaLaserMode",
    "MishaModulatorMode",
    "MishaRhythmInput",
    "MishaStereoDelayMode",
    "MixLaw",
    "ModSource",
    "Mode2",
    "Model",
    "MulSource",
    "MultivoicerMidiCh",
    "MultivoicerScale",
    "MultivoicerV1Interval",
    "MxPhase95Mode",
    "MxPhase95Type",
    "NollyCompressorAttack",
    "Notelength",
    "Octave",
    "Osc1Wave",
    "OutMode",
    "OverlordSynthScale",
    "Peak",
    "PetrucciChorus1Mode",
    "PetrucciPhaserMode",
    "PhaseLockedLoopMultiplier",
    "Pickup",
    "PitchPattern",
    "PliniChorusMode",
    "PliniDriveMode",
    "PreRoll",
    "Preset",
    "PunchMode",
    "Quality",
    "Quantize",
    "RabeaColossusFuzzMode",
    "Range",
    "Ratio3",
    "Ratio5",
    "ReadPoint",
    "RecLength",
    "RedDriveMode",
    "Resonance",
    "Response",
    "RingModulatorMultiplier",
    "RoomLDist",
    "RoomSize",
    "Root",
    "RotaryAttack",
    "Routing",
    "RoutingMode",
    "Size",
    "SlapbackDelayMSyncNote",
    "Slope",
    "SoldanoSlo100Channel",
    "Sound",
    "SplitterMode",
    "SplitterType",
    "Start",
    "Stereo",
    "StereoLink",
    "Sweep",
    "SyncNote11",
    "SyncNote14",
    "SyncNote17",
    "SyncNote21",
    "SyncOn",
    "SyncSource",
    "TankType",
    "Tap1Interval",
    "Tap1Semitones",
    "TapPreset",
    "TempoSource",
    "TempocontrolType",
    "TimHensonDelayModernMode",
    "TimeSignature",
    "TremoloWaveform",
    "TrigDirection",
    "Trigger",
    "TriggerMode",
    "Tube",
    "UnisonSource",
    "UsDlx64VintageMode",
    "V1Active",
    "VibNote",
    "VintageChorusMode",
    "Voice",
    "VoiceMode",
    "VoiceView",
    "Voicing",
    "OPTION_LABELS",
]
